output "openrun_load_balancer_hostname" {
  description = "Hostname of the OpenRun service load balancer."
  value       = module.openrun.load_balancer_hostname
}

output "openrun_load_balancer_ips" {
  description = "Static Elastic IPs attached to the OpenRun NLB (use for DNS A records)."
  value       = module.openrun.load_balancer_eip_addresses
}

output "openrun_dns_records" {
  description = "DNS records to create for OpenRun."
  value = {
    root_a         = "${var.openrun_default_domain} -> ${join(", ", module.openrun.load_balancer_eip_addresses)}"
    wildcard_a     = "*.${var.openrun_default_domain} -> ${join(", ", module.openrun.load_balancer_eip_addresses)}"
    root_cname     = "${var.openrun_default_domain} -> ${module.openrun.load_balancer_hostname}"
    wildcard_cname = "*.${var.openrun_default_domain} -> ${module.openrun.load_balancer_hostname}"
  }
}

output "openrun_oidc_callback_url" {
  description = "OIDC callback URL for OpenRun."
  value       = "https://${var.openrun_default_domain}/_openrun/auth/${var.openrun_oidc_name}/callback"
}

output "openrun_saml_acs_url" {
  description = "SAML ACS endpoint for OpenRun."
  value       = "https://${var.openrun_default_domain}/_openrun/sso/${var.openrun_saml_name}/acs"
}

output "openrun_saml_metadata_url" {
  description = "SAML metadata endpoint for OpenRun."
  value       = "https://${var.openrun_default_domain}/_openrun/sso/${var.openrun_saml_name}/metadata"
}

output "openrun_admin_password" {
  description = "OpenRun admin password generated by Terraform."
  value       = module.openrun.admin_password
  sensitive   = true
}

output "ecr_repository_url" {
  description = "ECR repository URL for OpenRun images."
  value       = module.ecr.repo_url
}

output "rds_endpoint" {
  description = "RDS endpoint for OpenRun."
  value       = module.rds.db_endpoint
}
