version: 2
project_name: openrun

release:
  github:
    owner: openrundev
    name: openrun
  name_template: "Release {{.Tag}}"
  draft: false
  prerelease: "auto"

before:
  hooks:
    - go mod download
    - go mod tidy
    - git clone --single-branch --depth 1 https://github.com/openrundev/appspecs.git
    - rm -rf appspecs/.git
    - rm -rf internal/server/appspecs
    - mv appspecs internal/server
    - git clone --single-branch --depth 1 https://github.com/openrundev/apps.git
    - cp internal/server/list_apps/embed.go .
    - rm -rf internal/server/list_apps
    - mv apps/openrun/list_apps internal/server
    - mv embed.go internal/server/list_apps/
    - rm -rf apps
    - go test -race ./...

builds:
  - id: openrun
    main: ./cmd/openrun
    binary: openrun
    flags:
      - -trimpath
    ldflags:
      - -w
      - -X github.com/openrundev/openrun/internal/types.gitCommit={{.ShortCommit}}
      - -X github.com/openrundev/openrun/internal/types.gitVersion={{.Version}}
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
      - freebsd
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: freebsd
        goarch: arm64
      - goos: windows
        goarch: arm64

nfpms:
  - file_name_template: "{{.ProjectName}}-{{.Tag}}-{{.Arch}}{{if .Arm}}{{.Arm}}{{end}}"
    homepage: https://openrun.dev/
    description: Open source alternative to Google Cloud Run and AWS App Runner.
    maintainer: Ajay Kidave <contact@openrun.dev>
    license: Apache 2.0
    vendor: ClaceIO LLC.
    formats:
      - deb
      - rpm
    contents:
      - src: /usr/bin/openrun
        dst: /usr/local/bin/openrun
        type: "symlink"

checksum:
  name_template: "SHA256SUMS"
  algorithm: sha256

archives:
  - name_template: "{{.ProjectName}}-{{.Tag}}-{{.Os}}-{{.Arch}}{{if .Arm}}{{.Arm}}{{end}}"
    wrap_in_directory: true
    format: zip
    files:
      - README.md
      - LICENSE
  - name_template: "{{.ProjectName}}-{{.Tag}}-{{.Os}}-{{.Arch}}{{if .Arm}}{{.Arm}}{{end}}"
    id: targz-archives
    wrap_in_directory: true
    format: tar.gz
    files:
      - README.md
      - LICENSE

# https://goreleaser.com/customization/changelog/
changelog:
  use: github
  sort: asc
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug Fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: "Dependencies"
      regexp: "^.*deps[(\\w)]*:+.*$"
      order: 30
    - title: Other
      order: 999

brews:
  - name: openrun
    homepage: https://openrun.dev
    ids: [targz-archives]
    repository:
      owner: openrundev
      name: homebrew-openrun
    dependencies:
      - name: "mkcert"
    service: |
      run [ opt_bin/"openrun", "server", "start" ]
      keep_alive true
      working_dir HOMEBREW_PREFIX
      log_path var/"log/openrun.log"
      error_log_path var/"log/openrun.log"
    skip_upload: auto
    install: |-
      bin.install "openrun"
    post_install: |-
      unless File.exist?("#{etc}/openrun.toml")
        pid = spawn("#{opt_bin}/openrun password", out: "#{etc}/openrun.toml")
        puts "********** Initializing \"admin\" user **********"
        Process.wait(pid)
        puts "************* Save this password ****************"

        mkcert_path = `which mkcert`.chomp
        unless mkcert_path.empty?
          system("mkdir -p #{HOMEBREW_PREFIX}/var/openrun/config/certificates")
          system("#{mkcert_path} -install")
          system("#{mkcert_path} -cert-file #{HOMEBREW_PREFIX}/var/openrun/config/certificates/default.crt -key-file #{HOMEBREW_PREFIX}/var/openrun/config/certificates/default.key localhost 127.0.0.1 \"*.localhost\"")
          puts "Created localhost TLS certificates"
        end
      end

# New images builder
dockers_v2:
  - id: openrun_img
    ids: [openrun]
    dockerfile: deploy/Dockerfile
    # Build both platforms and publish a single multi-arch manifest
    platforms: [linux/amd64, linux/arm64]
    images:
      - ghcr.io/openrundev/openrun
    tags:
      - "{{ .Version }}" # e.g. 1.2.3
      - "sha-{{ .ShortCommit }}"
      - latest
    labels:
      "org.opencontainers.image.title": "openrun"
      "org.opencontainers.image.description": "OpenRun: Declarative Web App Deployment"
      "org.opencontainers.image.source": "{{ .GitURL }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.created": "{{ .Date }}"
