// Copyright (c) ClaceIO, LLC
// SPDX-License-Identifier: Apache-2.0

package server

import (
	"cmp"
	"context"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/openrundev/openrun/internal/system"
	"github.com/openrundev/openrun/internal/types"
)

// appExportFields classifies every CreateAppRequest JSON field as handled by
// the exporter. A unit test walks CreateAppRequest with reflection and fails
// if a field is missing here, so schema additions cannot silently produce
// incomplete exports. When adding a field, update exportApp/formatApp (or
// document why it is not exportable) and then add it here.
var appExportFields = map[string]bool{
	"path":                 true,
	"source_url":           true,
	"is_dev":               true,
	"app_authn":            true,
	"git_branch":           true,
	"git_commit":           true,
	"git_auth_name":        true,
	"spec":                 true,
	"param_values":         true,
	"container_options":    true,
	"container_args":       true,
	"container_volumes":    true,
	"appconfig":            true,
	"bindings":             true,
	"binding_source_perms": true,
	"stage_at":             true,
	"verify":               true,
}

// bindingExportFields is the CreateBindingRequest equivalent of appExportFields.
// "-" is the ApplyInfo field, which is derived and not part of the config.
var bindingExportFields = map[string]bool{
	"path":   true,
	"source": true,
	"grants": true,
	"config": true,
	"-":      true,
}

// exportBuilder collects the prerequisites and warnings discovered while
// exporting, which are emitted as header comments in the generated config
type exportBuilder struct {
	opts             types.ExportOptions
	requiredServices map[string]bool
	serviceNames     map[string]map[string]bool // service type -> service names referenced
	gitAuthNames     map[string]bool
	authNames        map[string]bool
	localSources     map[string]bool
	defaultGitAuth   bool
	warnings         []string
}

func newExportBuilder(opts types.ExportOptions) *exportBuilder {
	return &exportBuilder{
		opts:             opts,
		requiredServices: map[string]bool{},
		serviceNames:     map[string]map[string]bool{},
		gitAuthNames:     map[string]bool{},
		authNames:        map[string]bool{},
		localSources:     map[string]bool{},
	}
}

func (b *exportBuilder) warnf(format string, args ...any) {
	b.warnings = append(b.warnings, fmt.Sprintf(format, args...))
}

// serviceRef returns the binding source to emit for a service-backed binding
// and records the service as a prerequisite
func (b *exportBuilder) serviceRef(binding *types.Binding) string {
	b.requiredServices[binding.ServiceType] = true
	if b.serviceNames[binding.ServiceType] == nil {
		b.serviceNames[binding.ServiceType] = map[string]bool{}
	}
	b.serviceNames[binding.ServiceType][binding.ServiceName] = true
	if b.opts.ServiceRef == types.ExportRefExact {
		return binding.ServiceType + "/" + binding.ServiceName
	}
	return binding.ServiceType
}

// header renders the collected prerequisites and warnings as comment lines
func (b *exportBuilder) header() string {
	lines := []string{
		"# Declarative app config generated by 'openrun export'.",
		"# Apply on an openrun instance with: openrun apply --approve <file>",
	}
	if len(b.requiredServices) > 0 {
		lines = append(lines, "# Requires services: "+strings.Join(sortedKeys(b.requiredServices), ", "))
	}
	if len(b.gitAuthNames) > 0 {
		lines = append(lines, "# Requires git_auth config entries: "+strings.Join(sortedKeys(b.gitAuthNames), ", "))
	}
	if b.defaultGitAuth {
		lines = append(lines, "# Git sources use the target instance's default_git_auth (if authentication is needed)")
	}
	if len(b.authNames) > 0 {
		lines = append(lines, "# Requires auth config entries: "+strings.Join(sortedKeys(b.authNames), ", "))
	}
	if len(b.localSources) > 0 {
		lines = append(lines, "# Local disk sources must exist on the target instance: "+strings.Join(sortedKeys(b.localSources), ", "))
	}
	if b.opts.ServiceRef == types.ExportRefDefault {
		for _, serviceType := range sortedKeys(b.serviceNames) {
			if len(b.serviceNames[serviceType]) > 1 {
				b.warnf("bindings referenced multiple %s services (%s); all are remapped to the default %s service",
					serviceType, strings.Join(sortedKeys(b.serviceNames[serviceType]), ", "), serviceType)
			}
		}
	}
	for _, warning := range b.warnings {
		lines = append(lines, "# WARNING: "+warning)
	}
	return strings.Join(lines, "\n") + "\n\n"
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	slices.Sort(keys)
	return keys
}

// Export writes the current prod state of apps and bindings as a declarative
// config file which can be re-applied with "openrun apply". Stage and preview
// state is not included; dev apps are exported with dev=True.
func (s *Server) Export(ctx context.Context, appPathGlob string, opts types.ExportOptions) (string, error) {
	opts.ServiceRef = cmp.Or(opts.ServiceRef, types.ExportRefDefault)
	opts.GitAuthRef = cmp.Or(opts.GitAuthRef, types.ExportRefDefault)
	if opts.ServiceRef != types.ExportRefDefault && opts.ServiceRef != types.ExportRefExact {
		return "", fmt.Errorf("invalid service-ref %q, expected %s or %s", opts.ServiceRef, types.ExportRefDefault, types.ExportRefExact)
	}
	if opts.GitAuthRef != types.ExportRefDefault && opts.GitAuthRef != types.ExportRefExact {
		return "", fmt.Errorf("invalid git-auth %q, expected %s or %s", opts.GitAuthRef, types.ExportRefDefault, types.ExportRefExact)
	}
	if err := s.enforceGlobalPerm(ctx, types.PermissionBindingRead, ""); err != nil {
		return "", err
	}

	tx, err := s.db.BeginTransaction(ctx)
	if err != nil {
		return "", err
	}
	defer tx.Rollback() //nolint:errcheck

	builder := newExportBuilder(opts)

	allBindings, err := s.db.ListBindings(ctx, tx, "")
	if err != nil {
		return "", err
	}
	bindingsByPath := make(map[string]*types.Binding, len(allBindings))
	for _, binding := range allBindings {
		bindingsByPath[binding.Path] = binding
	}
	bindingReqs := builder.exportBindings(allBindings)

	filteredApps, err := s.FilterApps(cmp.Or(appPathGlob, "all"), false)
	if err != nil {
		return "", err
	}
	slices.SortFunc(filteredApps, func(a, b types.AppInfo) int {
		if c := cmp.Compare(a.Domain, b.Domain); c != 0 {
			return c
		}
		return cmp.Compare(a.Path, b.Path)
	})

	userId := system.GetContextUserId(ctx)
	groups := system.GetContextGroups(ctx)
	appReqs := make([]*types.CreateAppRequest, 0, len(filteredApps))
	for _, app := range filteredApps {
		authorized, err := s.AuthorizeList(ctx, userId, &app, groups)
		if err != nil {
			return "", err
		}
		if !authorized {
			continue
		}
		appEntry, err := s.db.GetAppEntryTx(ctx, tx, app.AppPathDomain)
		if err != nil {
			return "", fmt.Errorf("error reading app %s: %w", app.AppPathDomain, err)
		}
		if opts.ExcludeDeclarative && len(appEntry.Metadata.VersionMetadata.ApplyInfo) > 0 {
			continue
		}
		appReqs = append(appReqs, s.exportApp(ctx, tx, appEntry, bindingsByPath, builder))
	}

	body, formatWarnings := formatConfig(bindingReqs, appReqs)
	builder.warnings = append(builder.warnings, formatWarnings...)
	return builder.header() + body, nil
}

// exportBindings converts the exportable bindings to binding() definitions.
// Auto bindings are not exported (they are recreated from the app bindings
// list) and derived bindings are ordered after the binding they derive from
func (b *exportBuilder) exportBindings(allBindings []*types.Binding) []*types.CreateBindingRequest {
	exportable := make([]*types.Binding, 0, len(allBindings))
	inExport := map[string]bool{}
	for _, binding := range allBindings {
		if strings.HasPrefix(binding.Path, autoBindingPathPrefix+"/") {
			continue
		}
		if b.opts.ExcludeDeclarative && len(binding.Metadata.ApplyInfo) > 0 {
			continue
		}
		exportable = append(exportable, binding)
		inExport[binding.Path] = true
	}
	slices.SortFunc(exportable, func(a, b *types.Binding) int {
		return cmp.Compare(a.Path, b.Path)
	})

	// Emit a derived binding after its base binding. A base excluded from the
	// export (declarative, with --exclude-declarative) is expected to already
	// exist on the target instance
	ordered := make([]*types.Binding, 0, len(exportable))
	emitted := map[string]bool{}
	for len(ordered) < len(exportable) {
		progress := false
		for _, binding := range exportable {
			if emitted[binding.Path] {
				continue
			}
			if binding.DerivedFrom == "" || emitted[binding.DerivedFrom] || !inExport[binding.DerivedFrom] {
				ordered = append(ordered, binding)
				emitted[binding.Path] = true
				progress = true
			}
		}
		if !progress { // derivation cycle, should not happen; emit the rest as is
			for _, binding := range exportable {
				if !emitted[binding.Path] {
					ordered = append(ordered, binding)
					emitted[binding.Path] = true
				}
			}
		}
	}

	ret := make([]*types.CreateBindingRequest, 0, len(ordered))
	for _, binding := range ordered {
		source := binding.DerivedFrom
		if source == "" {
			source = b.serviceRef(binding)
		} else if !inExport[source] {
			b.warnf("binding %s derives from %s which is declaratively managed and not exported; apply its config first", binding.Path, source)
		}
		ret = append(ret, &types.CreateBindingRequest{
			Path:   binding.Path,
			Source: source,
			Grants: binding.Metadata.Grants,
			Config: binding.Metadata.Config,
		})
	}
	return ret
}

// exportApp builds the app() definition for the current prod version of an app
func (s *Server) exportApp(ctx context.Context, tx types.Transaction, appEntry *types.AppEntry,
	bindingsByPath map[string]*types.Binding, builder *exportBuilder) *types.CreateAppRequest {
	metadata := &appEntry.Metadata
	req := &types.CreateAppRequest{
		Path:               appEntry.String(),
		SourceUrl:          appEntry.SourceUrl,
		IsDev:              appEntry.IsDev,
		Spec:               metadata.Spec,
		ParamValues:        metadata.ParamValues,
		AppConfig:          metadata.AppConfig,
		ContainerOptions:   metadata.ContainerOptions,
		ContainerArgs:      metadata.ContainerArgs,
		ContainerVolumes:   metadata.ContainerVolumes,
		BindingSourcePerms: metadata.BindingSourcePerms,
	}

	// The deprecated AppSettings auth fields are migrated into AppMetadata on
	// server upgrade (migrateAuthSettings), so Metadata is authoritative here
	auth := metadata.AuthnType
	if auth != "" && auth != types.AppAuthnDefault {
		req.AppAuthn = auth
		if auth != types.AppAuthnNone && auth != types.AppAuthnSystem {
			builder.authNames[string(auth)] = true
		}
	}

	if system.IsGit(appEntry.SourceUrl) {
		req.GitBranch = metadata.VersionMetadata.GitBranch
		if builder.opts.ExactCommit {
			req.GitCommit = metadata.VersionMetadata.GitCommit
		}
		gitAuth := metadata.GitAuthName
		if builder.opts.GitAuthRef == types.ExportRefExact && gitAuth != "" {
			req.GitAuthName = gitAuth
			builder.gitAuthNames[gitAuth] = true
		} else {
			builder.defaultGitAuth = true
		}
	} else {
		builder.localSources[appEntry.SourceUrl] = true
	}

	for _, bindingRef := range metadata.Bindings {
		if !strings.HasPrefix(bindingRef, autoBindingPathPrefix+"/") {
			req.Bindings = append(req.Bindings, bindingRef)
			continue
		}
		autoBinding := bindingsByPath[bindingRef]
		if autoBinding == nil {
			builder.warnf("app %s references auto binding %s which no longer exists; reference dropped", req.Path, bindingRef)
			continue
		}
		req.Bindings = append(req.Bindings, builder.serviceRef(autoBinding))
	}

	req.StageAt = s.deriveStageAt(ctx, tx, appEntry, builder)
	return req
}

// deriveStageAt reverse-derives the stage_at value from where the app's stage
// app actually lives. When the stage location matches this server's default,
// stage_at is omitted so the output stays concise
func (s *Server) deriveStageAt(ctx context.Context, tx types.Transaction, appEntry *types.AppEntry, builder *exportBuilder) string {
	if appEntry.IsDev || !strings.HasPrefix(string(appEntry.Id), types.ID_PREFIX_APP_PROD) {
		return ""
	}
	stageApp, err := s.getStageApp(ctx, tx, appEntry)
	if err != nil {
		builder.warnf("could not resolve stage app for %s: %s", appEntry.String(), err)
		return ""
	}
	actual := stageApp.AppPathDomain()
	prodApp := appEntry.AppPathDomain()
	if derived, err := s.stageAppPathDomain(prodApp, ""); err == nil && derived == actual {
		return "" // matches the server default
	}
	for _, mode := range []string{"path", "domain"} {
		if derived, err := s.stageAppPathDomain(prodApp, mode); err == nil && derived == actual {
			return mode
		}
	}
	if actual.Path == prodApp.Path {
		return actual.Domain // custom stage domain
	}
	builder.warnf("stage app for %s is at %s which no stage_at value reproduces; stage_at omitted", appEntry.String(), actual)
	return ""
}

// PrettyPrint parses an existing declarative config file and re-emits it in
// the canonical format used by export. Starlark logic (conditionals, config()
// lookups, helper functions) is evaluated and replaced with literal values
func (s *Server) PrettyPrint(ctx context.Context, applyPath string) (string, error) {
	if system.IsGit(applyPath) {
		return "", fmt.Errorf("pretty-print supports local files only, not git urls")
	}
	fileInfo, err := os.Stat(applyPath)
	if err != nil {
		return "", err
	}
	if fileInfo.IsDir() {
		return "", fmt.Errorf("%s is a directory, expected a config file", applyPath)
	}
	data, err := os.ReadFile(applyPath)
	if err != nil {
		return "", err
	}
	appReqs, bindingReqs, err := s.loadApplyInfo(filepath.Base(applyPath), data, "", false)
	if err != nil {
		return "", err
	}
	body, warnings := formatConfig(bindingReqs, appReqs)
	var sb strings.Builder
	for _, warning := range warnings {
		sb.WriteString("# WARNING: " + warning + "\n")
	}
	sb.WriteString(body)
	return sb.String(), nil
}
