// Copyright (c) ClaceIO, LLC
// SPDX-License-Identifier: Apache-2.0

// Wire contract between the OpenRun server and out-of-process binding
// providers. This proto is the single source of truth for the provider
// protocol; the server and the provider SDK each map it to their own Go types.
//
// Application-level failures are carried in the response `error` field, not as
// gRPC status errors: GenerateAccount must return already-created artifacts
// together with an error so the server can roll them back. gRPC status errors
// are reserved for transport failures (provider crash, protocol mismatch),
// which the server treats as retryable by respawning the provider.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.4
// source: binding.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BindingProvider_Describe_FullMethodName          = "/openrun.binding.v1.BindingProvider/Describe"
	BindingProvider_GetAccountEnv_FullMethodName     = "/openrun.binding.v1.BindingProvider/GetAccountEnv"
	BindingProvider_InitializeService_FullMethodName = "/openrun.binding.v1.BindingProvider/InitializeService"
	BindingProvider_CloseService_FullMethodName      = "/openrun.binding.v1.BindingProvider/CloseService"
	BindingProvider_GenerateAccount_FullMethodName   = "/openrun.binding.v1.BindingProvider/GenerateAccount"
	BindingProvider_DeleteArtifact_FullMethodName    = "/openrun.binding.v1.BindingProvider/DeleteArtifact"
	BindingProvider_ApplyGrants_FullMethodName       = "/openrun.binding.v1.BindingProvider/ApplyGrants"
	BindingProvider_RevokeGrants_FullMethodName      = "/openrun.binding.v1.BindingProvider/RevokeGrants"
	BindingProvider_RunCommand_FullMethodName        = "/openrun.binding.v1.BindingProvider/RunCommand"
)

// BindingProviderClient is the client API for BindingProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BindingProviderClient interface {
	// Describe reports the service types served by this provider binary and
	// their config schemas. Valid before InitializeService.
	Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error)
	// GetAccountEnv reports the names of the env values included in the binding
	// account info for a service type: the always-present params, then the
	// optional params. Static info; valid before InitializeService.
	GetAccountEnv(ctx context.Context, in *GetAccountEnvRequest, opts ...grpc.CallOption) (*GetAccountEnvResponse, error)
	InitializeService(ctx context.Context, in *InitializeServiceRequest, opts ...grpc.CallOption) (*InitializeServiceResponse, error)
	CloseService(ctx context.Context, in *CloseServiceRequest, opts ...grpc.CallOption) (*CloseServiceResponse, error)
	GenerateAccount(ctx context.Context, in *GenerateAccountRequest, opts ...grpc.CallOption) (*GenerateAccountResponse, error)
	DeleteArtifact(ctx context.Context, in *DeleteArtifactRequest, opts ...grpc.CallOption) (*DeleteArtifactResponse, error)
	ApplyGrants(ctx context.Context, in *ApplyGrantsRequest, opts ...grpc.CallOption) (*ApplyGrantsResponse, error)
	RevokeGrants(ctx context.Context, in *RevokeGrantsRequest, opts ...grpc.CallOption) (*RevokeGrantsResponse, error)
	RunCommand(ctx context.Context, in *RunCommandRequest, opts ...grpc.CallOption) (*RunCommandResponse, error)
}

type bindingProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewBindingProviderClient(cc grpc.ClientConnInterface) BindingProviderClient {
	return &bindingProviderClient{cc}
}

func (c *bindingProviderClient) Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeResponse)
	err := c.cc.Invoke(ctx, BindingProvider_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bindingProviderClient) GetAccountEnv(ctx context.Context, in *GetAccountEnvRequest, opts ...grpc.CallOption) (*GetAccountEnvResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAccountEnvResponse)
	err := c.cc.Invoke(ctx, BindingProvider_GetAccountEnv_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bindingProviderClient) InitializeService(ctx context.Context, in *InitializeServiceRequest, opts ...grpc.CallOption) (*InitializeServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitializeServiceResponse)
	err := c.cc.Invoke(ctx, BindingProvider_InitializeService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bindingProviderClient) CloseService(ctx context.Context, in *CloseServiceRequest, opts ...grpc.CallOption) (*CloseServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseServiceResponse)
	err := c.cc.Invoke(ctx, BindingProvider_CloseService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bindingProviderClient) GenerateAccount(ctx context.Context, in *GenerateAccountRequest, opts ...grpc.CallOption) (*GenerateAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateAccountResponse)
	err := c.cc.Invoke(ctx, BindingProvider_GenerateAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bindingProviderClient) DeleteArtifact(ctx context.Context, in *DeleteArtifactRequest, opts ...grpc.CallOption) (*DeleteArtifactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteArtifactResponse)
	err := c.cc.Invoke(ctx, BindingProvider_DeleteArtifact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bindingProviderClient) ApplyGrants(ctx context.Context, in *ApplyGrantsRequest, opts ...grpc.CallOption) (*ApplyGrantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyGrantsResponse)
	err := c.cc.Invoke(ctx, BindingProvider_ApplyGrants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bindingProviderClient) RevokeGrants(ctx context.Context, in *RevokeGrantsRequest, opts ...grpc.CallOption) (*RevokeGrantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeGrantsResponse)
	err := c.cc.Invoke(ctx, BindingProvider_RevokeGrants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bindingProviderClient) RunCommand(ctx context.Context, in *RunCommandRequest, opts ...grpc.CallOption) (*RunCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunCommandResponse)
	err := c.cc.Invoke(ctx, BindingProvider_RunCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BindingProviderServer is the server API for BindingProvider service.
// All implementations must embed UnimplementedBindingProviderServer
// for forward compatibility.
type BindingProviderServer interface {
	// Describe reports the service types served by this provider binary and
	// their config schemas. Valid before InitializeService.
	Describe(context.Context, *DescribeRequest) (*DescribeResponse, error)
	// GetAccountEnv reports the names of the env values included in the binding
	// account info for a service type: the always-present params, then the
	// optional params. Static info; valid before InitializeService.
	GetAccountEnv(context.Context, *GetAccountEnvRequest) (*GetAccountEnvResponse, error)
	InitializeService(context.Context, *InitializeServiceRequest) (*InitializeServiceResponse, error)
	CloseService(context.Context, *CloseServiceRequest) (*CloseServiceResponse, error)
	GenerateAccount(context.Context, *GenerateAccountRequest) (*GenerateAccountResponse, error)
	DeleteArtifact(context.Context, *DeleteArtifactRequest) (*DeleteArtifactResponse, error)
	ApplyGrants(context.Context, *ApplyGrantsRequest) (*ApplyGrantsResponse, error)
	RevokeGrants(context.Context, *RevokeGrantsRequest) (*RevokeGrantsResponse, error)
	RunCommand(context.Context, *RunCommandRequest) (*RunCommandResponse, error)
	mustEmbedUnimplementedBindingProviderServer()
}

// UnimplementedBindingProviderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBindingProviderServer struct{}

func (UnimplementedBindingProviderServer) Describe(context.Context, *DescribeRequest) (*DescribeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedBindingProviderServer) GetAccountEnv(context.Context, *GetAccountEnvRequest) (*GetAccountEnvResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAccountEnv not implemented")
}
func (UnimplementedBindingProviderServer) InitializeService(context.Context, *InitializeServiceRequest) (*InitializeServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitializeService not implemented")
}
func (UnimplementedBindingProviderServer) CloseService(context.Context, *CloseServiceRequest) (*CloseServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseService not implemented")
}
func (UnimplementedBindingProviderServer) GenerateAccount(context.Context, *GenerateAccountRequest) (*GenerateAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateAccount not implemented")
}
func (UnimplementedBindingProviderServer) DeleteArtifact(context.Context, *DeleteArtifactRequest) (*DeleteArtifactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteArtifact not implemented")
}
func (UnimplementedBindingProviderServer) ApplyGrants(context.Context, *ApplyGrantsRequest) (*ApplyGrantsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyGrants not implemented")
}
func (UnimplementedBindingProviderServer) RevokeGrants(context.Context, *RevokeGrantsRequest) (*RevokeGrantsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeGrants not implemented")
}
func (UnimplementedBindingProviderServer) RunCommand(context.Context, *RunCommandRequest) (*RunCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunCommand not implemented")
}
func (UnimplementedBindingProviderServer) mustEmbedUnimplementedBindingProviderServer() {}
func (UnimplementedBindingProviderServer) testEmbeddedByValue()                         {}

// UnsafeBindingProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BindingProviderServer will
// result in compilation errors.
type UnsafeBindingProviderServer interface {
	mustEmbedUnimplementedBindingProviderServer()
}

func RegisterBindingProviderServer(s grpc.ServiceRegistrar, srv BindingProviderServer) {
	// If the following call panics, it indicates UnimplementedBindingProviderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BindingProvider_ServiceDesc, srv)
}

func _BindingProvider_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BindingProviderServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BindingProvider_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BindingProviderServer).Describe(ctx, req.(*DescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BindingProvider_GetAccountEnv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountEnvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BindingProviderServer).GetAccountEnv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BindingProvider_GetAccountEnv_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BindingProviderServer).GetAccountEnv(ctx, req.(*GetAccountEnvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BindingProvider_InitializeService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitializeServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BindingProviderServer).InitializeService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BindingProvider_InitializeService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BindingProviderServer).InitializeService(ctx, req.(*InitializeServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BindingProvider_CloseService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BindingProviderServer).CloseService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BindingProvider_CloseService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BindingProviderServer).CloseService(ctx, req.(*CloseServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BindingProvider_GenerateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BindingProviderServer).GenerateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BindingProvider_GenerateAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BindingProviderServer).GenerateAccount(ctx, req.(*GenerateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BindingProvider_DeleteArtifact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteArtifactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BindingProviderServer).DeleteArtifact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BindingProvider_DeleteArtifact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BindingProviderServer).DeleteArtifact(ctx, req.(*DeleteArtifactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BindingProvider_ApplyGrants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyGrantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BindingProviderServer).ApplyGrants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BindingProvider_ApplyGrants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BindingProviderServer).ApplyGrants(ctx, req.(*ApplyGrantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BindingProvider_RevokeGrants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeGrantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BindingProviderServer).RevokeGrants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BindingProvider_RevokeGrants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BindingProviderServer).RevokeGrants(ctx, req.(*RevokeGrantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BindingProvider_RunCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BindingProviderServer).RunCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BindingProvider_RunCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BindingProviderServer).RunCommand(ctx, req.(*RunCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BindingProvider_ServiceDesc is the grpc.ServiceDesc for BindingProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BindingProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openrun.binding.v1.BindingProvider",
	HandlerType: (*BindingProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _BindingProvider_Describe_Handler,
		},
		{
			MethodName: "GetAccountEnv",
			Handler:    _BindingProvider_GetAccountEnv_Handler,
		},
		{
			MethodName: "InitializeService",
			Handler:    _BindingProvider_InitializeService_Handler,
		},
		{
			MethodName: "CloseService",
			Handler:    _BindingProvider_CloseService_Handler,
		},
		{
			MethodName: "GenerateAccount",
			Handler:    _BindingProvider_GenerateAccount_Handler,
		},
		{
			MethodName: "DeleteArtifact",
			Handler:    _BindingProvider_DeleteArtifact_Handler,
		},
		{
			MethodName: "ApplyGrants",
			Handler:    _BindingProvider_ApplyGrants_Handler,
		},
		{
			MethodName: "RevokeGrants",
			Handler:    _BindingProvider_RevokeGrants_Handler,
		},
		{
			MethodName: "RunCommand",
			Handler:    _BindingProvider_RunCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "binding.proto",
}
