// Copyright (c) ClaceIO, LLC
// SPDX-License-Identifier: Apache-2.0

// Wire contract between the OpenRun server and out-of-process binding
// providers. This proto is the single source of truth for the provider
// protocol; the server and the provider SDK each map it to their own Go types.
//
// Application-level failures are carried in the response `error` field, not as
// gRPC status errors: GenerateAccount must return already-created artifacts
// together with an error so the server can roll them back. gRPC status errors
// are reserved for transport failures (provider crash, protocol mismatch),
// which the server treats as retryable by respawning the provider.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: binding.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BindingMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grants        []string               `protobuf:"bytes,1,rep,name=grants,proto3" json:"grants,omitempty"`
	GrantsApplied []*BindingGrant        `protobuf:"bytes,2,rep,name=grants_applied,json=grantsApplied,proto3" json:"grants_applied,omitempty"`
	Config        map[string]string      `protobuf:"bytes,3,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Account       map[string]string      `protobuf:"bytes,4,rep,name=account,proto3" json:"account,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ApplyInfo     []byte                 `protobuf:"bytes,5,opt,name=apply_info,json=applyInfo,proto3" json:"apply_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindingMetadata) Reset() {
	*x = BindingMetadata{}
	mi := &file_binding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindingMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindingMetadata) ProtoMessage() {}

func (x *BindingMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_binding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindingMetadata.ProtoReflect.Descriptor instead.
func (*BindingMetadata) Descriptor() ([]byte, []int) {
	return file_binding_proto_rawDescGZIP(), []int{0}
}

func (x *BindingMetadata) GetGrants() []string {
	if x != nil {
		return x.Grants
	}
	return nil
}

func (x *BindingMetadata) GetGrantsApplied() []*BindingGrant {
	if x != nil {
		return x.GrantsApplied
	}
	return nil
}

func (x *BindingMetadata) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *BindingMetadata) GetAccount() map[string]string {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *BindingMetadata) GetApplyInfo() []byte {
	if x != nil {
		return x.ApplyInfo
	}
	return nil
}

type BindingGrant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GrantType     string                 `protobuf:"bytes,1,opt,name=grant_type,json=grantType,proto3" json:"grant_type,omitempty"`
	GrantTarget   string                 `protobuf:"bytes,2,opt,name=grant_target,json=grantTarget,proto3" json:"grant_target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindingGrant) Reset() {
	*x = BindingGrant{}
	mi := &file_binding_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindingGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindingGrant) ProtoMessage() {}

func (x *BindingGrant) ProtoReflect() protoreflect.Message {
	mi := &file_binding_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindingGrant.ProtoReflect.Descriptor instead.
func (*BindingGrant) Descriptor() ([]byte, []int) {
	return file_binding_proto_rawDescGZIP(), []int{1}
}

func (x *BindingGrant) GetGrantType() string {
	if x != nil {
		return x.GrantType
	}
	return ""
}

func (x *BindingGrant) GetGrantTarget() string {
	if x != nil {
		return x.GrantTarget
	}
	return ""
}

type Artifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_binding_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_binding_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_binding_proto_rawDescGZIP(), []int{2}
}

func (x *Artifact) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Artifact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DescribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeRequest) Reset() {
	*x = DescribeRequest{}
	mi := &file_binding_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRequest) ProtoMessage() {}

func (x *DescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_binding_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRequest.ProtoReflect.Descriptor instead.
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return file_binding_proto_rawDescGZIP(), []int{3}
}

type DescribeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProviderVersion string                 `protobuf:"bytes,1,opt,name=provider_version,json=providerVersion,proto3" json:"provider_version,omitempty"`
	ServiceTypes    []*ServiceTypeInfo     `protobuf:"bytes,2,rep,name=service_types,json=serviceTypes,proto3" json:"service_types,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DescribeResponse) Reset() {
	*x = DescribeResponse{}
	mi := &file_binding_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse) ProtoMessage() {}

func (x *DescribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_binding_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse.ProtoReflect.Descriptor instead.
func (*DescribeResponse) Descriptor() ([]byte, []int) {
	return file_binding_proto_rawDescGZIP(), []int{4}
}

func (x *DescribeResponse) GetProviderVersion() string {
	if x != nil {
		return x.ProviderVersion
	}
	return ""
}

func (x *DescribeResponse) GetServiceTypes() []*ServiceTypeInfo {
	if x != nil {
		return x.ServiceTypes
	}
	return nil
}

type ServiceTypeInfo struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ServiceType         string                 `protobuf:"bytes,1,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`
	SupportedGrantTypes []string               `protobuf:"bytes,2,rep,name=supported_grant_types,json=supportedGrantTypes,proto3" json:"supported_grant_types,omitempty"`
	RequiredConfigKeys  []string               `protobuf:"bytes,3,rep,name=required_config_keys,json=requiredConfigKeys,proto3" json:"required_config_keys,omitempty"`
	OptionalConfigKeys  []string               `protobuf:"bytes,4,rep,name=optional_config_keys,json=optionalConfigKeys,proto3" json:"optional_config_keys,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ServiceTypeInfo) Reset() {
	*x = ServiceTypeInfo{}
	mi := &file_binding_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceTypeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTypeInfo) ProtoMessage() {}

func (x *ServiceTypeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_binding_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTypeInfo.ProtoReflect.Descriptor instead.
func (*ServiceTypeInfo) Descriptor() ([]byte, []int) {
	return file_binding_proto_rawDescGZIP(), []int{5}
}

func (x *ServiceTypeInfo) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

func (x *ServiceTypeInfo) GetSupportedGrantTypes() []string {
	if x != nil {
		return x.SupportedGrantTypes
	}
	return nil
}

func (x *ServiceTypeInfo) GetRequiredConfigKeys() []string {
	if x != nil {
		return x.RequiredConfigKeys
	}
	return nil
}

func (x *ServiceTypeInfo) GetOptionalConfigKeys() []string {
	if x != nil {
		return x.OptionalConfigKeys
	}
	return nil
}

type GetAccountEnvRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceType   string                 `protobuf:"bytes,1,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountEnvRequest) Reset() {
	*x = GetAccountEnvRequest{}
	mi := &file_binding_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountEnvRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountEnvRequest) ProtoMessage() {}

func (x *GetAccountEnvRequest) ProtoReflect() protoreflect.Message {
	mi := &file_binding_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountEnvRequest.ProtoReflect.Descriptor instead.
func (*GetAccountEnvRequest) Descriptor() ([]byte, []int) {
	return file_binding_proto_rawDescGZIP(), []int{6}
}

func (x *GetAccountEnvRequest) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

type GetAccountEnvResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Params         []string               `protobuf:"bytes,1,rep,name=params,proto3" json:"params,omitempty"`
	OptionalParams []string               `protobuf:"bytes,2,rep,name=optional_params,json=optionalParams,proto3" json:"optional_params,omitempty"`
	Error          string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetAccountEnvResponse) Reset() {
	*x = GetAccountEnvResponse{}
	mi := &file_binding_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountEnvResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountEnvResponse) ProtoMessage() {}

func (x *GetAccountEnvResponse) ProtoReflect() protoreflect.Message {
	mi := &file_binding_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountEnvResponse.ProtoReflect.Descriptor instead.
func (*GetAccountEnvResponse) Descriptor() ([]byte, []int) {
	return file_binding_proto_rawDescGZIP(), []int{7}
}

func (x *GetAccountEnvResponse) GetParams() []string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *GetAccountEnvResponse) GetOptionalParams() []string {
	if x != nil {
		return x.OptionalParams
	}
	return nil
}

func (x *GetAccountEnvResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type InitializeServiceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The service type to serve; one provider binary may implement several.
	ServiceType   string            `protobuf:"bytes,1,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`
	ServiceConfig map[string]string `protobuf:"bytes,2,rep,name=service_config,json=serviceConfig,proto3" json:"service_config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// ServiceBindingRuntime, flattened.
	LocalhostBindingHostname string `protobuf:"bytes,3,opt,name=localhost_binding_hostname,json=localhostBindingHostname,proto3" json:"localhost_binding_hostname,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *InitializeServiceRequest) Reset() {
	*x = InitializeServiceRequest{}
	mi := &file_binding_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeServiceRequest) ProtoMessage() {}

func (x *InitializeServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_binding_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeServiceRequest.ProtoReflect.Descriptor instead.
func (*InitializeServiceRequest) Descriptor() ([]byte, []int) {
	return file_binding_proto_rawDescGZIP(), []int{8}
}

func (x *InitializeServiceRequest) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

func (x *InitializeServiceRequest) GetServiceConfig() map[string]string {
	if x != nil {
		return x.ServiceConfig
	}
	return nil
}

func (x *InitializeServiceRequest) GetLocalhostBindingHostname() string {
	if x != nil {
		return x.LocalhostBindingHostname
	}
	return ""
}

type InitializeServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeServiceResponse) Reset() {
	*x = InitializeServiceResponse{}
	mi := &file_binding_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeServiceResponse) ProtoMessage() {}

func (x *InitializeServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_binding_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeServiceResponse.ProtoReflect.Descriptor instead.
func (*InitializeServiceResponse) Descriptor() ([]byte, []int) {
	return file_binding_proto_rawDescGZIP(), []int{9}
}

func (x *InitializeServiceResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CloseServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseServiceRequest) Reset() {
	*x = CloseServiceRequest{}
	mi := &file_binding_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseServiceRequest) ProtoMessage() {}

func (x *CloseServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_binding_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseServiceRequest.ProtoReflect.Descriptor instead.
func (*CloseServiceRequest) Descriptor() ([]byte, []int) {
	return file_binding_proto_rawDescGZIP(), []int{10}
}

type CloseServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseServiceResponse) Reset() {
	*x = CloseServiceResponse{}
	mi := &file_binding_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseServiceResponse) ProtoMessage() {}

func (x *CloseServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_binding_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseServiceResponse.ProtoReflect.Descriptor instead.
func (*CloseServiceResponse) Descriptor() ([]byte, []int) {
	return file_binding_proto_rawDescGZIP(), []int{11}
}

func (x *CloseServiceResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GenerateAccountRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	BindingId           string                 `protobuf:"bytes,1,opt,name=binding_id,json=bindingId,proto3" json:"binding_id,omitempty"`
	BindingPath         string                 `protobuf:"bytes,2,opt,name=binding_path,json=bindingPath,proto3" json:"binding_path,omitempty"`
	BindingMetadata     *BindingMetadata       `protobuf:"bytes,3,opt,name=binding_metadata,json=bindingMetadata,proto3" json:"binding_metadata,omitempty"`
	DerivedFromMetadata *BindingMetadata       `protobuf:"bytes,4,opt,name=derived_from_metadata,json=derivedFromMetadata,proto3,oneof" json:"derived_from_metadata,omitempty"`
	IsStaging           bool                   `protobuf:"varint,5,opt,name=is_staging,json=isStaging,proto3" json:"is_staging,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GenerateAccountRequest) Reset() {
	*x = GenerateAccountRequest{}
	mi := &file_binding_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateAccountRequest) ProtoMessage() {}

func (x *GenerateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_binding_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateAccountRequest.ProtoReflect.Descriptor instead.
func (*GenerateAccountRequest) Descriptor() ([]byte, []int) {
	return file_binding_proto_rawDescGZIP(), []int{12}
}

func (x *GenerateAccountRequest) GetBindingId() string {
	if x != nil {
		return x.BindingId
	}
	return ""
}

func (x *GenerateAccountRequest) GetBindingPath() string {
	if x != nil {
		return x.BindingPath
	}
	return ""
}

func (x *GenerateAccountRequest) GetBindingMetadata() *BindingMetadata {
	if x != nil {
		return x.BindingMetadata
	}
	return nil
}

func (x *GenerateAccountRequest) GetDerivedFromMetadata() *BindingMetadata {
	if x != nil {
		return x.DerivedFromMetadata
	}
	return nil
}

func (x *GenerateAccountRequest) GetIsStaging() bool {
	if x != nil {
		return x.IsStaging
	}
	return false
}

type GenerateAccountResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Account map[string]string      `protobuf:"bytes,1,rep,name=account,proto3" json:"account,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Artifacts created on the service, in creation order. Populated even when
	// error is set, so the caller can clean up after a partial failure.
	CreatedArtifacts []*Artifact `protobuf:"bytes,2,rep,name=created_artifacts,json=createdArtifacts,proto3" json:"created_artifacts,omitempty"`
	Error            string      `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GenerateAccountResponse) Reset() {
	*x = GenerateAccountResponse{}
	mi := &file_binding_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateAccountResponse) ProtoMessage() {}

func (x *GenerateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_binding_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateAccountResponse.ProtoReflect.Descriptor instead.
func (*GenerateAccountResponse) Descriptor() ([]byte, []int) {
	return file_binding_proto_rawDescGZIP(), []int{13}
}

func (x *GenerateAccountResponse) GetAccount() map[string]string {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *GenerateAccountResponse) GetCreatedArtifacts() []*Artifact {
	if x != nil {
		return x.CreatedArtifacts
	}
	return nil
}

func (x *GenerateAccountResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteArtifactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artifact      *Artifact              `protobuf:"bytes,1,opt,name=artifact,proto3" json:"artifact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArtifactRequest) Reset() {
	*x = DeleteArtifactRequest{}
	mi := &file_binding_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArtifactRequest) ProtoMessage() {}

func (x *DeleteArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_binding_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArtifactRequest.ProtoReflect.Descriptor instead.
func (*DeleteArtifactRequest) Descriptor() ([]byte, []int) {
	return file_binding_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteArtifactRequest) GetArtifact() *Artifact {
	if x != nil {
		return x.Artifact
	}
	return nil
}

type DeleteArtifactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArtifactResponse) Reset() {
	*x = DeleteArtifactResponse{}
	mi := &file_binding_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArtifactResponse) ProtoMessage() {}

func (x *DeleteArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_binding_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArtifactResponse.ProtoReflect.Descriptor instead.
func (*DeleteArtifactResponse) Descriptor() ([]byte, []int) {
	return file_binding_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteArtifactResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ApplyGrantsRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Account             map[string]string      `protobuf:"bytes,1,rep,name=account,proto3" json:"account,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	BindingMetadata     *BindingMetadata       `protobuf:"bytes,2,opt,name=binding_metadata,json=bindingMetadata,proto3" json:"binding_metadata,omitempty"`
	DerivedFromMetadata *BindingMetadata       `protobuf:"bytes,3,opt,name=derived_from_metadata,json=derivedFromMetadata,proto3" json:"derived_from_metadata,omitempty"`
	ReapplyAll          bool                   `protobuf:"varint,4,opt,name=reapply_all,json=reapplyAll,proto3" json:"reapply_all,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ApplyGrantsRequest) Reset() {
	*x = ApplyGrantsRequest{}
	mi := &file_binding_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyGrantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyGrantsRequest) ProtoMessage() {}

func (x *ApplyGrantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_binding_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyGrantsRequest.ProtoReflect.Descriptor instead.
func (*ApplyGrantsRequest) Descriptor() ([]byte, []int) {
	return file_binding_proto_rawDescGZIP(), []int{16}
}

func (x *ApplyGrantsRequest) GetAccount() map[string]string {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *ApplyGrantsRequest) GetBindingMetadata() *BindingMetadata {
	if x != nil {
		return x.BindingMetadata
	}
	return nil
}

func (x *ApplyGrantsRequest) GetDerivedFromMetadata() *BindingMetadata {
	if x != nil {
		return x.DerivedFromMetadata
	}
	return nil
}

func (x *ApplyGrantsRequest) GetReapplyAll() bool {
	if x != nil {
		return x.ReapplyAll
	}
	return false
}

type ApplyGrantsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	GrantsApplied  []*BindingGrant        `protobuf:"bytes,1,rep,name=grants_applied,json=grantsApplied,proto3" json:"grants_applied,omitempty"`
	Granted        []*BindingGrant        `protobuf:"bytes,2,rep,name=granted,proto3" json:"granted,omitempty"`
	PendingRevokes []*BindingGrant        `protobuf:"bytes,3,rep,name=pending_revokes,json=pendingRevokes,proto3" json:"pending_revokes,omitempty"`
	Error          string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApplyGrantsResponse) Reset() {
	*x = ApplyGrantsResponse{}
	mi := &file_binding_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyGrantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyGrantsResponse) ProtoMessage() {}

func (x *ApplyGrantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_binding_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyGrantsResponse.ProtoReflect.Descriptor instead.
func (*ApplyGrantsResponse) Descriptor() ([]byte, []int) {
	return file_binding_proto_rawDescGZIP(), []int{17}
}

func (x *ApplyGrantsResponse) GetGrantsApplied() []*BindingGrant {
	if x != nil {
		return x.GrantsApplied
	}
	return nil
}

func (x *ApplyGrantsResponse) GetGranted() []*BindingGrant {
	if x != nil {
		return x.Granted
	}
	return nil
}

func (x *ApplyGrantsResponse) GetPendingRevokes() []*BindingGrant {
	if x != nil {
		return x.PendingRevokes
	}
	return nil
}

func (x *ApplyGrantsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RevokeGrantsRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Account             map[string]string      `protobuf:"bytes,1,rep,name=account,proto3" json:"account,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DerivedFromMetadata *BindingMetadata       `protobuf:"bytes,2,opt,name=derived_from_metadata,json=derivedFromMetadata,proto3" json:"derived_from_metadata,omitempty"`
	Revokes             []*BindingGrant        `protobuf:"bytes,3,rep,name=revokes,proto3" json:"revokes,omitempty"`
	Regrants            []*BindingGrant        `protobuf:"bytes,4,rep,name=regrants,proto3" json:"regrants,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RevokeGrantsRequest) Reset() {
	*x = RevokeGrantsRequest{}
	mi := &file_binding_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeGrantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeGrantsRequest) ProtoMessage() {}

func (x *RevokeGrantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_binding_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeGrantsRequest.ProtoReflect.Descriptor instead.
func (*RevokeGrantsRequest) Descriptor() ([]byte, []int) {
	return file_binding_proto_rawDescGZIP(), []int{18}
}

func (x *RevokeGrantsRequest) GetAccount() map[string]string {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *RevokeGrantsRequest) GetDerivedFromMetadata() *BindingMetadata {
	if x != nil {
		return x.DerivedFromMetadata
	}
	return nil
}

func (x *RevokeGrantsRequest) GetRevokes() []*BindingGrant {
	if x != nil {
		return x.Revokes
	}
	return nil
}

func (x *RevokeGrantsRequest) GetRegrants() []*BindingGrant {
	if x != nil {
		return x.Regrants
	}
	return nil
}

type RevokeGrantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeGrantsResponse) Reset() {
	*x = RevokeGrantsResponse{}
	mi := &file_binding_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeGrantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeGrantsResponse) ProtoMessage() {}

func (x *RevokeGrantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_binding_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeGrantsResponse.ProtoReflect.Descriptor instead.
func (*RevokeGrantsResponse) Descriptor() ([]byte, []int) {
	return file_binding_proto_rawDescGZIP(), []int{19}
}

func (x *RevokeGrantsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RunCommandRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BindingMetadata *BindingMetadata       `protobuf:"bytes,1,opt,name=binding_metadata,json=bindingMetadata,proto3" json:"binding_metadata,omitempty"`
	Command         string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RunCommandRequest) Reset() {
	*x = RunCommandRequest{}
	mi := &file_binding_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCommandRequest) ProtoMessage() {}

func (x *RunCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_binding_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCommandRequest.ProtoReflect.Descriptor instead.
func (*RunCommandRequest) Descriptor() ([]byte, []int) {
	return file_binding_proto_rawDescGZIP(), []int{20}
}

func (x *RunCommandRequest) GetBindingMetadata() *BindingMetadata {
	if x != nil {
		return x.BindingMetadata
	}
	return nil
}

func (x *RunCommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type RunCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *structpb.Struct       `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCommandResponse) Reset() {
	*x = RunCommandResponse{}
	mi := &file_binding_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCommandResponse) ProtoMessage() {}

func (x *RunCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_binding_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCommandResponse.ProtoReflect.Descriptor instead.
func (*RunCommandResponse) Descriptor() ([]byte, []int) {
	return file_binding_proto_rawDescGZIP(), []int{21}
}

func (x *RunCommandResponse) GetResult() *structpb.Struct {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *RunCommandResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_binding_proto protoreflect.FileDescriptor

const file_binding_proto_rawDesc = "" +
	"\n" +
	"\rbinding.proto\x12\x12openrun.binding.v1\x1a\x1cgoogle/protobuf/struct.proto\"\x9d\x03\n" +
	"\x0fBindingMetadata\x12\x16\n" +
	"\x06grants\x18\x01 \x03(\tR\x06grants\x12G\n" +
	"\x0egrants_applied\x18\x02 \x03(\v2 .openrun.binding.v1.BindingGrantR\rgrantsApplied\x12G\n" +
	"\x06config\x18\x03 \x03(\v2/.openrun.binding.v1.BindingMetadata.ConfigEntryR\x06config\x12J\n" +
	"\aaccount\x18\x04 \x03(\v20.openrun.binding.v1.BindingMetadata.AccountEntryR\aaccount\x12\x1d\n" +
	"\n" +
	"apply_info\x18\x05 \x01(\fR\tapplyInfo\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fAccountEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"P\n" +
	"\fBindingGrant\x12\x1d\n" +
	"\n" +
	"grant_type\x18\x01 \x01(\tR\tgrantType\x12!\n" +
	"\fgrant_target\x18\x02 \x01(\tR\vgrantTarget\"2\n" +
	"\bArtifact\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x11\n" +
	"\x0fDescribeRequest\"\x87\x01\n" +
	"\x10DescribeResponse\x12)\n" +
	"\x10provider_version\x18\x01 \x01(\tR\x0fproviderVersion\x12H\n" +
	"\rservice_types\x18\x02 \x03(\v2#.openrun.binding.v1.ServiceTypeInfoR\fserviceTypes\"\xcc\x01\n" +
	"\x0fServiceTypeInfo\x12!\n" +
	"\fservice_type\x18\x01 \x01(\tR\vserviceType\x122\n" +
	"\x15supported_grant_types\x18\x02 \x03(\tR\x13supportedGrantTypes\x120\n" +
	"\x14required_config_keys\x18\x03 \x03(\tR\x12requiredConfigKeys\x120\n" +
	"\x14optional_config_keys\x18\x04 \x03(\tR\x12optionalConfigKeys\"9\n" +
	"\x14GetAccountEnvRequest\x12!\n" +
	"\fservice_type\x18\x01 \x01(\tR\vserviceType\"n\n" +
	"\x15GetAccountEnvResponse\x12\x16\n" +
	"\x06params\x18\x01 \x03(\tR\x06params\x12'\n" +
	"\x0foptional_params\x18\x02 \x03(\tR\x0eoptionalParams\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xa5\x02\n" +
	"\x18InitializeServiceRequest\x12!\n" +
	"\fservice_type\x18\x01 \x01(\tR\vserviceType\x12f\n" +
	"\x0eservice_config\x18\x02 \x03(\v2?.openrun.binding.v1.InitializeServiceRequest.ServiceConfigEntryR\rserviceConfig\x12<\n" +
	"\x1alocalhost_binding_hostname\x18\x03 \x01(\tR\x18localhostBindingHostname\x1a@\n" +
	"\x12ServiceConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"1\n" +
	"\x19InitializeServiceResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\x15\n" +
	"\x13CloseServiceRequest\",\n" +
	"\x14CloseServiceResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\xc1\x02\n" +
	"\x16GenerateAccountRequest\x12\x1d\n" +
	"\n" +
	"binding_id\x18\x01 \x01(\tR\tbindingId\x12!\n" +
	"\fbinding_path\x18\x02 \x01(\tR\vbindingPath\x12N\n" +
	"\x10binding_metadata\x18\x03 \x01(\v2#.openrun.binding.v1.BindingMetadataR\x0fbindingMetadata\x12\\\n" +
	"\x15derived_from_metadata\x18\x04 \x01(\v2#.openrun.binding.v1.BindingMetadataH\x00R\x13derivedFromMetadata\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"is_staging\x18\x05 \x01(\bR\tisStagingB\x18\n" +
	"\x16_derived_from_metadata\"\x8a\x02\n" +
	"\x17GenerateAccountResponse\x12R\n" +
	"\aaccount\x18\x01 \x03(\v28.openrun.binding.v1.GenerateAccountResponse.AccountEntryR\aaccount\x12I\n" +
	"\x11created_artifacts\x18\x02 \x03(\v2\x1c.openrun.binding.v1.ArtifactR\x10createdArtifacts\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x1a:\n" +
	"\fAccountEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Q\n" +
	"\x15DeleteArtifactRequest\x128\n" +
	"\bartifact\x18\x01 \x01(\v2\x1c.openrun.binding.v1.ArtifactR\bartifact\".\n" +
	"\x16DeleteArtifactResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\xe9\x02\n" +
	"\x12ApplyGrantsRequest\x12M\n" +
	"\aaccount\x18\x01 \x03(\v23.openrun.binding.v1.ApplyGrantsRequest.AccountEntryR\aaccount\x12N\n" +
	"\x10binding_metadata\x18\x02 \x01(\v2#.openrun.binding.v1.BindingMetadataR\x0fbindingMetadata\x12W\n" +
	"\x15derived_from_metadata\x18\x03 \x01(\v2#.openrun.binding.v1.BindingMetadataR\x13derivedFromMetadata\x12\x1f\n" +
	"\vreapply_all\x18\x04 \x01(\bR\n" +
	"reapplyAll\x1a:\n" +
	"\fAccountEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfb\x01\n" +
	"\x13ApplyGrantsResponse\x12G\n" +
	"\x0egrants_applied\x18\x01 \x03(\v2 .openrun.binding.v1.BindingGrantR\rgrantsApplied\x12:\n" +
	"\agranted\x18\x02 \x03(\v2 .openrun.binding.v1.BindingGrantR\agranted\x12I\n" +
	"\x0fpending_revokes\x18\x03 \x03(\v2 .openrun.binding.v1.BindingGrantR\x0ependingRevokes\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\xf4\x02\n" +
	"\x13RevokeGrantsRequest\x12N\n" +
	"\aaccount\x18\x01 \x03(\v24.openrun.binding.v1.RevokeGrantsRequest.AccountEntryR\aaccount\x12W\n" +
	"\x15derived_from_metadata\x18\x02 \x01(\v2#.openrun.binding.v1.BindingMetadataR\x13derivedFromMetadata\x12:\n" +
	"\arevokes\x18\x03 \x03(\v2 .openrun.binding.v1.BindingGrantR\arevokes\x12<\n" +
	"\bregrants\x18\x04 \x03(\v2 .openrun.binding.v1.BindingGrantR\bregrants\x1a:\n" +
	"\fAccountEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\",\n" +
	"\x14RevokeGrantsResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"}\n" +
	"\x11RunCommandRequest\x12N\n" +
	"\x10binding_metadata\x18\x01 \x01(\v2#.openrun.binding.v1.BindingMetadataR\x0fbindingMetadata\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\"[\n" +
	"\x12RunCommandResponse\x12/\n" +
	"\x06result\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x06result\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\x98\a\n" +
	"\x0fBindingProvider\x12U\n" +
	"\bDescribe\x12#.openrun.binding.v1.DescribeRequest\x1a$.openrun.binding.v1.DescribeResponse\x12d\n" +
	"\rGetAccountEnv\x12(.openrun.binding.v1.GetAccountEnvRequest\x1a).openrun.binding.v1.GetAccountEnvResponse\x12p\n" +
	"\x11InitializeService\x12,.openrun.binding.v1.InitializeServiceRequest\x1a-.openrun.binding.v1.InitializeServiceResponse\x12a\n" +
	"\fCloseService\x12'.openrun.binding.v1.CloseServiceRequest\x1a(.openrun.binding.v1.CloseServiceResponse\x12j\n" +
	"\x0fGenerateAccount\x12*.openrun.binding.v1.GenerateAccountRequest\x1a+.openrun.binding.v1.GenerateAccountResponse\x12g\n" +
	"\x0eDeleteArtifact\x12).openrun.binding.v1.DeleteArtifactRequest\x1a*.openrun.binding.v1.DeleteArtifactResponse\x12^\n" +
	"\vApplyGrants\x12&.openrun.binding.v1.ApplyGrantsRequest\x1a'.openrun.binding.v1.ApplyGrantsResponse\x12a\n" +
	"\fRevokeGrants\x12'.openrun.binding.v1.RevokeGrantsRequest\x1a(.openrun.binding.v1.RevokeGrantsResponse\x12[\n" +
	"\n" +
	"RunCommand\x12%.openrun.binding.v1.RunCommandRequest\x1a&.openrun.binding.v1.RunCommandResponseB1Z/github.com/openrundev/openrun/pkg/binding/protob\x06proto3"

var (
	file_binding_proto_rawDescOnce sync.Once
	file_binding_proto_rawDescData []byte
)

func file_binding_proto_rawDescGZIP() []byte {
	file_binding_proto_rawDescOnce.Do(func() {
		file_binding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_binding_proto_rawDesc), len(file_binding_proto_rawDesc)))
	})
	return file_binding_proto_rawDescData
}

var file_binding_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_binding_proto_goTypes = []any{
	(*BindingMetadata)(nil),           // 0: openrun.binding.v1.BindingMetadata
	(*BindingGrant)(nil),              // 1: openrun.binding.v1.BindingGrant
	(*Artifact)(nil),                  // 2: openrun.binding.v1.Artifact
	(*DescribeRequest)(nil),           // 3: openrun.binding.v1.DescribeRequest
	(*DescribeResponse)(nil),          // 4: openrun.binding.v1.DescribeResponse
	(*ServiceTypeInfo)(nil),           // 5: openrun.binding.v1.ServiceTypeInfo
	(*GetAccountEnvRequest)(nil),      // 6: openrun.binding.v1.GetAccountEnvRequest
	(*GetAccountEnvResponse)(nil),     // 7: openrun.binding.v1.GetAccountEnvResponse
	(*InitializeServiceRequest)(nil),  // 8: openrun.binding.v1.InitializeServiceRequest
	(*InitializeServiceResponse)(nil), // 9: openrun.binding.v1.InitializeServiceResponse
	(*CloseServiceRequest)(nil),       // 10: openrun.binding.v1.CloseServiceRequest
	(*CloseServiceResponse)(nil),      // 11: openrun.binding.v1.CloseServiceResponse
	(*GenerateAccountRequest)(nil),    // 12: openrun.binding.v1.GenerateAccountRequest
	(*GenerateAccountResponse)(nil),   // 13: openrun.binding.v1.GenerateAccountResponse
	(*DeleteArtifactRequest)(nil),     // 14: openrun.binding.v1.DeleteArtifactRequest
	(*DeleteArtifactResponse)(nil),    // 15: openrun.binding.v1.DeleteArtifactResponse
	(*ApplyGrantsRequest)(nil),        // 16: openrun.binding.v1.ApplyGrantsRequest
	(*ApplyGrantsResponse)(nil),       // 17: openrun.binding.v1.ApplyGrantsResponse
	(*RevokeGrantsRequest)(nil),       // 18: openrun.binding.v1.RevokeGrantsRequest
	(*RevokeGrantsResponse)(nil),      // 19: openrun.binding.v1.RevokeGrantsResponse
	(*RunCommandRequest)(nil),         // 20: openrun.binding.v1.RunCommandRequest
	(*RunCommandResponse)(nil),        // 21: openrun.binding.v1.RunCommandResponse
	nil,                               // 22: openrun.binding.v1.BindingMetadata.ConfigEntry
	nil,                               // 23: openrun.binding.v1.BindingMetadata.AccountEntry
	nil,                               // 24: openrun.binding.v1.InitializeServiceRequest.ServiceConfigEntry
	nil,                               // 25: openrun.binding.v1.GenerateAccountResponse.AccountEntry
	nil,                               // 26: openrun.binding.v1.ApplyGrantsRequest.AccountEntry
	nil,                               // 27: openrun.binding.v1.RevokeGrantsRequest.AccountEntry
	(*structpb.Struct)(nil),           // 28: google.protobuf.Struct
}
var file_binding_proto_depIdxs = []int32{
	1,  // 0: openrun.binding.v1.BindingMetadata.grants_applied:type_name -> openrun.binding.v1.BindingGrant
	22, // 1: openrun.binding.v1.BindingMetadata.config:type_name -> openrun.binding.v1.BindingMetadata.ConfigEntry
	23, // 2: openrun.binding.v1.BindingMetadata.account:type_name -> openrun.binding.v1.BindingMetadata.AccountEntry
	5,  // 3: openrun.binding.v1.DescribeResponse.service_types:type_name -> openrun.binding.v1.ServiceTypeInfo
	24, // 4: openrun.binding.v1.InitializeServiceRequest.service_config:type_name -> openrun.binding.v1.InitializeServiceRequest.ServiceConfigEntry
	0,  // 5: openrun.binding.v1.GenerateAccountRequest.binding_metadata:type_name -> openrun.binding.v1.BindingMetadata
	0,  // 6: openrun.binding.v1.GenerateAccountRequest.derived_from_metadata:type_name -> openrun.binding.v1.BindingMetadata
	25, // 7: openrun.binding.v1.GenerateAccountResponse.account:type_name -> openrun.binding.v1.GenerateAccountResponse.AccountEntry
	2,  // 8: openrun.binding.v1.GenerateAccountResponse.created_artifacts:type_name -> openrun.binding.v1.Artifact
	2,  // 9: openrun.binding.v1.DeleteArtifactRequest.artifact:type_name -> openrun.binding.v1.Artifact
	26, // 10: openrun.binding.v1.ApplyGrantsRequest.account:type_name -> openrun.binding.v1.ApplyGrantsRequest.AccountEntry
	0,  // 11: openrun.binding.v1.ApplyGrantsRequest.binding_metadata:type_name -> openrun.binding.v1.BindingMetadata
	0,  // 12: openrun.binding.v1.ApplyGrantsRequest.derived_from_metadata:type_name -> openrun.binding.v1.BindingMetadata
	1,  // 13: openrun.binding.v1.ApplyGrantsResponse.grants_applied:type_name -> openrun.binding.v1.BindingGrant
	1,  // 14: openrun.binding.v1.ApplyGrantsResponse.granted:type_name -> openrun.binding.v1.BindingGrant
	1,  // 15: openrun.binding.v1.ApplyGrantsResponse.pending_revokes:type_name -> openrun.binding.v1.BindingGrant
	27, // 16: openrun.binding.v1.RevokeGrantsRequest.account:type_name -> openrun.binding.v1.RevokeGrantsRequest.AccountEntry
	0,  // 17: openrun.binding.v1.RevokeGrantsRequest.derived_from_metadata:type_name -> openrun.binding.v1.BindingMetadata
	1,  // 18: openrun.binding.v1.RevokeGrantsRequest.revokes:type_name -> openrun.binding.v1.BindingGrant
	1,  // 19: openrun.binding.v1.RevokeGrantsRequest.regrants:type_name -> openrun.binding.v1.BindingGrant
	0,  // 20: openrun.binding.v1.RunCommandRequest.binding_metadata:type_name -> openrun.binding.v1.BindingMetadata
	28, // 21: openrun.binding.v1.RunCommandResponse.result:type_name -> google.protobuf.Struct
	3,  // 22: openrun.binding.v1.BindingProvider.Describe:input_type -> openrun.binding.v1.DescribeRequest
	6,  // 23: openrun.binding.v1.BindingProvider.GetAccountEnv:input_type -> openrun.binding.v1.GetAccountEnvRequest
	8,  // 24: openrun.binding.v1.BindingProvider.InitializeService:input_type -> openrun.binding.v1.InitializeServiceRequest
	10, // 25: openrun.binding.v1.BindingProvider.CloseService:input_type -> openrun.binding.v1.CloseServiceRequest
	12, // 26: openrun.binding.v1.BindingProvider.GenerateAccount:input_type -> openrun.binding.v1.GenerateAccountRequest
	14, // 27: openrun.binding.v1.BindingProvider.DeleteArtifact:input_type -> openrun.binding.v1.DeleteArtifactRequest
	16, // 28: openrun.binding.v1.BindingProvider.ApplyGrants:input_type -> openrun.binding.v1.ApplyGrantsRequest
	18, // 29: openrun.binding.v1.BindingProvider.RevokeGrants:input_type -> openrun.binding.v1.RevokeGrantsRequest
	20, // 30: openrun.binding.v1.BindingProvider.RunCommand:input_type -> openrun.binding.v1.RunCommandRequest
	4,  // 31: openrun.binding.v1.BindingProvider.Describe:output_type -> openrun.binding.v1.DescribeResponse
	7,  // 32: openrun.binding.v1.BindingProvider.GetAccountEnv:output_type -> openrun.binding.v1.GetAccountEnvResponse
	9,  // 33: openrun.binding.v1.BindingProvider.InitializeService:output_type -> openrun.binding.v1.InitializeServiceResponse
	11, // 34: openrun.binding.v1.BindingProvider.CloseService:output_type -> openrun.binding.v1.CloseServiceResponse
	13, // 35: openrun.binding.v1.BindingProvider.GenerateAccount:output_type -> openrun.binding.v1.GenerateAccountResponse
	15, // 36: openrun.binding.v1.BindingProvider.DeleteArtifact:output_type -> openrun.binding.v1.DeleteArtifactResponse
	17, // 37: openrun.binding.v1.BindingProvider.ApplyGrants:output_type -> openrun.binding.v1.ApplyGrantsResponse
	19, // 38: openrun.binding.v1.BindingProvider.RevokeGrants:output_type -> openrun.binding.v1.RevokeGrantsResponse
	21, // 39: openrun.binding.v1.BindingProvider.RunCommand:output_type -> openrun.binding.v1.RunCommandResponse
	31, // [31:40] is the sub-list for method output_type
	22, // [22:31] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_binding_proto_init() }
func file_binding_proto_init() {
	if File_binding_proto != nil {
		return
	}
	file_binding_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_binding_proto_rawDesc), len(file_binding_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_binding_proto_goTypes,
		DependencyIndexes: file_binding_proto_depIdxs,
		MessageInfos:      file_binding_proto_msgTypes,
	}.Build()
	File_binding_proto = out.File
	file_binding_proto_goTypes = nil
	file_binding_proto_depIdxs = nil
}
