// Copyright (c) ClaceIO, LLC
// SPDX-License-Identifier: Apache-2.0

// Wire contract between the OpenRun server and out-of-process Starlark plugin
// providers (modules loaded in apps with load("name.ex", ...)). This proto is
// the single source of truth for the plugin provider protocol; the server and
// the provider SDK each map it to their own Go types.
//
// Application-level failures are carried in the response `error` field, not as
// gRPC status errors: a plugin call error feeds the app's PluginResponse error
// handling (response.error / error_handler). gRPC status errors are reserved
// for transport failures (provider crash, protocol mismatch); the server kills
// the provider process, fails the request's live sessions, and respawns the
// process on the next request. Plugin calls are never retried automatically.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StarValue is the wire representation of a Starlark value. Full fidelity is
// preserved for the value shapes plugin calls can carry: big ints stay exact,
// int and float stay distinct types, tuples/sets/bytes are not folded into
// lists/strings, and dict entry order is preserved.
type StarValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*StarValue_None
	//	*StarValue_Bool
	//	*StarValue_Int
	//	*StarValue_Bigint
	//	*StarValue_Float
	//	*StarValue_Str
	//	*StarValue_Bytes
	//	*StarValue_List
	//	*StarValue_Tuple
	//	*StarValue_Set
	//	*StarValue_Dict
	//	*StarValue_Struct
	//	*StarValue_TimeUnixNanos
	//	*StarValue_Cursor
	//	*StarValue_Thunk
	//	*StarValue_Funcref
	Kind          isStarValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StarValue) Reset() {
	*x = StarValue{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarValue) ProtoMessage() {}

func (x *StarValue) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarValue.ProtoReflect.Descriptor instead.
func (*StarValue) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *StarValue) GetKind() isStarValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *StarValue) GetNone() bool {
	if x != nil {
		if x, ok := x.Kind.(*StarValue_None); ok {
			return x.None
		}
	}
	return false
}

func (x *StarValue) GetBool() bool {
	if x != nil {
		if x, ok := x.Kind.(*StarValue_Bool); ok {
			return x.Bool
		}
	}
	return false
}

func (x *StarValue) GetInt() int64 {
	if x != nil {
		if x, ok := x.Kind.(*StarValue_Int); ok {
			return x.Int
		}
	}
	return 0
}

func (x *StarValue) GetBigint() *BigInt {
	if x != nil {
		if x, ok := x.Kind.(*StarValue_Bigint); ok {
			return x.Bigint
		}
	}
	return nil
}

func (x *StarValue) GetFloat() float64 {
	if x != nil {
		if x, ok := x.Kind.(*StarValue_Float); ok {
			return x.Float
		}
	}
	return 0
}

func (x *StarValue) GetStr() string {
	if x != nil {
		if x, ok := x.Kind.(*StarValue_Str); ok {
			return x.Str
		}
	}
	return ""
}

func (x *StarValue) GetBytes() []byte {
	if x != nil {
		if x, ok := x.Kind.(*StarValue_Bytes); ok {
			return x.Bytes
		}
	}
	return nil
}

func (x *StarValue) GetList() *ValueList {
	if x != nil {
		if x, ok := x.Kind.(*StarValue_List); ok {
			return x.List
		}
	}
	return nil
}

func (x *StarValue) GetTuple() *ValueList {
	if x != nil {
		if x, ok := x.Kind.(*StarValue_Tuple); ok {
			return x.Tuple
		}
	}
	return nil
}

func (x *StarValue) GetSet() *ValueList {
	if x != nil {
		if x, ok := x.Kind.(*StarValue_Set); ok {
			return x.Set
		}
	}
	return nil
}

func (x *StarValue) GetDict() *StarDict {
	if x != nil {
		if x, ok := x.Kind.(*StarValue_Dict); ok {
			return x.Dict
		}
	}
	return nil
}

func (x *StarValue) GetStruct() *TypedStruct {
	if x != nil {
		if x, ok := x.Kind.(*StarValue_Struct); ok {
			return x.Struct
		}
	}
	return nil
}

func (x *StarValue) GetTimeUnixNanos() int64 {
	if x != nil {
		if x, ok := x.Kind.(*StarValue_TimeUnixNanos); ok {
			return x.TimeUnixNanos
		}
	}
	return 0
}

func (x *StarValue) GetCursor() *Cursor {
	if x != nil {
		if x, ok := x.Kind.(*StarValue_Cursor); ok {
			return x.Cursor
		}
	}
	return nil
}

func (x *StarValue) GetThunk() *Thunk {
	if x != nil {
		if x, ok := x.Kind.(*StarValue_Thunk); ok {
			return x.Thunk
		}
	}
	return nil
}

func (x *StarValue) GetFuncref() *FuncRef {
	if x != nil {
		if x, ok := x.Kind.(*StarValue_Funcref); ok {
			return x.Funcref
		}
	}
	return nil
}

type isStarValue_Kind interface {
	isStarValue_Kind()
}

type StarValue_None struct {
	None bool `protobuf:"varint,1,opt,name=none,proto3,oneof"` // presence marker; the bool value is ignored
}

type StarValue_Bool struct {
	Bool bool `protobuf:"varint,2,opt,name=bool,proto3,oneof"`
}

type StarValue_Int struct {
	Int int64 `protobuf:"varint,3,opt,name=int,proto3,oneof"` // fast path for ints representable in 64 bits
}

type StarValue_Bigint struct {
	Bigint *BigInt `protobuf:"bytes,4,opt,name=bigint,proto3,oneof"`
}

type StarValue_Float struct {
	Float float64 `protobuf:"fixed64,5,opt,name=float,proto3,oneof"`
}

type StarValue_Str struct {
	Str string `protobuf:"bytes,6,opt,name=str,proto3,oneof"`
}

type StarValue_Bytes struct {
	Bytes []byte `protobuf:"bytes,7,opt,name=bytes,proto3,oneof"`
}

type StarValue_List struct {
	List *ValueList `protobuf:"bytes,8,opt,name=list,proto3,oneof"`
}

type StarValue_Tuple struct {
	Tuple *ValueList `protobuf:"bytes,9,opt,name=tuple,proto3,oneof"`
}

type StarValue_Set struct {
	Set *ValueList `protobuf:"bytes,10,opt,name=set,proto3,oneof"`
}

type StarValue_Dict struct {
	Dict *StarDict `protobuf:"bytes,11,opt,name=dict,proto3,oneof"`
}

type StarValue_Struct struct {
	Struct *TypedStruct `protobuf:"bytes,12,opt,name=struct,proto3,oneof"` // schema-typed record (attribute access)
}

type StarValue_TimeUnixNanos struct {
	TimeUnixNanos int64 `protobuf:"varint,13,opt,name=time_unix_nanos,json=timeUnixNanos,proto3,oneof"` // starlark time.time
}

type StarValue_Cursor struct {
	Cursor *Cursor `protobuf:"bytes,14,opt,name=cursor,proto3,oneof"` // handle to a provider-side lazy iterator
}

type StarValue_Thunk struct {
	Thunk *Thunk `protobuf:"bytes,15,opt,name=thunk,proto3,oneof"` // zero-arg callable over pre-computed data
}

type StarValue_Funcref struct {
	Funcref *FuncRef `protobuf:"bytes,16,opt,name=funcref,proto3,oneof"` // zero-arg callable dispatching a plugin function
}

func (*StarValue_None) isStarValue_Kind() {}

func (*StarValue_Bool) isStarValue_Kind() {}

func (*StarValue_Int) isStarValue_Kind() {}

func (*StarValue_Bigint) isStarValue_Kind() {}

func (*StarValue_Float) isStarValue_Kind() {}

func (*StarValue_Str) isStarValue_Kind() {}

func (*StarValue_Bytes) isStarValue_Kind() {}

func (*StarValue_List) isStarValue_Kind() {}

func (*StarValue_Tuple) isStarValue_Kind() {}

func (*StarValue_Set) isStarValue_Kind() {}

func (*StarValue_Dict) isStarValue_Kind() {}

func (*StarValue_Struct) isStarValue_Kind() {}

func (*StarValue_TimeUnixNanos) isStarValue_Kind() {}

func (*StarValue_Cursor) isStarValue_Kind() {}

func (*StarValue_Thunk) isStarValue_Kind() {}

func (*StarValue_Funcref) isStarValue_Kind() {}

// FuncRef carries a value the server materializes as a zero-argument
// callable: calling it invokes the named plugin function with args, in the
// same module, account, and session as the call that returned it. Function
// names starting with "_" are internal: not exposed as module attributes,
// callable only through a FuncRef.
type FuncRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Function      string                 `protobuf:"bytes,1,opt,name=function,proto3" json:"function,omitempty"`
	Args          []*StarValue           `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FuncRef) Reset() {
	*x = FuncRef{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FuncRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuncRef) ProtoMessage() {}

func (x *FuncRef) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuncRef.ProtoReflect.Descriptor instead.
func (*FuncRef) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *FuncRef) GetFunction() string {
	if x != nil {
		return x.Function
	}
	return ""
}

func (x *FuncRef) GetArgs() []*StarValue {
	if x != nil {
		return x.Args
	}
	return nil
}

// Thunk carries a value the server materializes as a zero-argument callable
// in the app: calling it returns the value, or fails with error if set. Used
// for records with callable members over pre-computed data, e.g. the http
// plugin's response.body() and response.json().
type Thunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // callable name, for error messages
	Value         *StarValue             `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Thunk) Reset() {
	*x = Thunk{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Thunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Thunk) ProtoMessage() {}

func (x *Thunk) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Thunk.ProtoReflect.Descriptor instead.
func (*Thunk) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *Thunk) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Thunk) GetValue() *StarValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Thunk) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BigInt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Negative      bool                   `protobuf:"varint,1,opt,name=negative,proto3" json:"negative,omitempty"`
	Abs           []byte                 `protobuf:"bytes,2,opt,name=abs,proto3" json:"abs,omitempty"` // big-endian absolute value, big.Int.Bytes()
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BigInt) Reset() {
	*x = BigInt{}
	mi := &file_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BigInt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BigInt) ProtoMessage() {}

func (x *BigInt) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BigInt.ProtoReflect.Descriptor instead.
func (*BigInt) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *BigInt) GetNegative() bool {
	if x != nil {
		return x.Negative
	}
	return false
}

func (x *BigInt) GetAbs() []byte {
	if x != nil {
		return x.Abs
	}
	return nil
}

type ValueList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*StarValue           `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueList) Reset() {
	*x = ValueList{}
	mi := &file_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueList) ProtoMessage() {}

func (x *ValueList) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueList.ProtoReflect.Descriptor instead.
func (*ValueList) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *ValueList) GetValues() []*StarValue {
	if x != nil {
		return x.Values
	}
	return nil
}

type StarDict struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*StarEntry           `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"` // insertion order preserved
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StarDict) Reset() {
	*x = StarDict{}
	mi := &file_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarDict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarDict) ProtoMessage() {}

func (x *StarDict) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarDict.ProtoReflect.Descriptor instead.
func (*StarDict) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *StarDict) GetEntries() []*StarEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type StarEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *StarValue             `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *StarValue             `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StarEntry) Reset() {
	*x = StarEntry{}
	mi := &file_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarEntry) ProtoMessage() {}

func (x *StarEntry) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarEntry.ProtoReflect.Descriptor instead.
func (*StarEntry) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *StarEntry) GetKey() *StarValue {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *StarEntry) GetValue() *StarValue {
	if x != nil {
		return x.Value
	}
	return nil
}

// TypedStruct carries a schema-typed record: the server materializes it as a
// StarlarkType (attribute access, mutable fields), matching what builtin
// plugins return for typed values.
type TypedStruct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeName      string                 `protobuf:"bytes,1,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	Fields        *StarDict              `protobuf:"bytes,2,opt,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypedStruct) Reset() {
	*x = TypedStruct{}
	mi := &file_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypedStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypedStruct) ProtoMessage() {}

func (x *TypedStruct) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypedStruct.ProtoReflect.Descriptor instead.
func (*TypedStruct) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *TypedStruct) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *TypedStruct) GetFields() *StarDict {
	if x != nil {
		return x.Fields
	}
	return nil
}

// Cursor is a handle to a lazy result iterator that stays in the provider
// process, scoped to the session that created it. The server wraps it in a
// Starlark iterable that batches CursorNext calls; leak_key names the strict
// deferred-cleanup entry the server registers so an unconsumed cursor fails
// the request the same way an unconsumed builtin cursor does.
type Cursor struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	CursorId string                 `protobuf:"bytes,1,opt,name=cursor_id,json=cursorId,proto3" json:"cursor_id,omitempty"`
	TypeName string                 `protobuf:"bytes,2,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"` // Starlark Type() is "<type_name> iterator"
	LeakKey  string                 `protobuf:"bytes,3,opt,name=leak_key,json=leakKey,proto3" json:"leak_key,omitempty"`
	// Stream cursors are returned from the app handler as streaming HTTP
	// responses instead of being iterated in Starlark. Supported for
	// in-process modules only; reserved here for protocol completeness.
	Stream        bool `protobuf:"varint,4,opt,name=stream,proto3" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cursor) Reset() {
	*x = Cursor{}
	mi := &file_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cursor) ProtoMessage() {}

func (x *Cursor) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cursor.ProtoReflect.Descriptor instead.
func (*Cursor) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *Cursor) GetCursorId() string {
	if x != nil {
		return x.CursorId
	}
	return ""
}

func (x *Cursor) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *Cursor) GetLeakKey() string {
	if x != nil {
		return x.LeakKey
	}
	return ""
}

func (x *Cursor) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

type DescribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeRequest) Reset() {
	*x = DescribeRequest{}
	mi := &file_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRequest) ProtoMessage() {}

func (x *DescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRequest.ProtoReflect.Descriptor instead.
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{9}
}

type DescribeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProviderVersion string                 `protobuf:"bytes,1,opt,name=provider_version,json=providerVersion,proto3" json:"provider_version,omitempty"`
	Modules         []*ModuleManifest      `protobuf:"bytes,2,rep,name=modules,proto3" json:"modules,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DescribeResponse) Reset() {
	*x = DescribeResponse{}
	mi := &file_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse) ProtoMessage() {}

func (x *DescribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse.ProtoReflect.Descriptor instead.
func (*DescribeResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *DescribeResponse) GetProviderVersion() string {
	if x != nil {
		return x.ProviderVersion
	}
	return ""
}

func (x *DescribeResponse) GetModules() []*ModuleManifest {
	if x != nil {
		return x.Modules
	}
	return nil
}

type ModuleManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // module "store" is loaded as "store.ex"
	Functions     []*FunctionManifest    `protobuf:"bytes,2,rep,name=functions,proto3" json:"functions,omitempty"`
	Constants     map[string]*StarValue  `protobuf:"bytes,3,rep,name=constants,proto3" json:"constants,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleManifest) Reset() {
	*x = ModuleManifest{}
	mi := &file_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleManifest) ProtoMessage() {}

func (x *ModuleManifest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleManifest.ProtoReflect.Descriptor instead.
func (*ModuleManifest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *ModuleManifest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModuleManifest) GetFunctions() []*FunctionManifest {
	if x != nil {
		return x.Functions
	}
	return nil
}

func (x *ModuleManifest) GetConstants() map[string]*StarValue {
	if x != nil {
		return x.Constants
	}
	return nil
}

type FunctionManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsRead        bool                   `protobuf:"varint,2,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"` // drives stage/preview write gating on the server
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionManifest) Reset() {
	*x = FunctionManifest{}
	mi := &file_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionManifest) ProtoMessage() {}

func (x *FunctionManifest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionManifest.ProtoReflect.Descriptor instead.
func (*FunctionManifest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *FunctionManifest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionManifest) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

type InitAppRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	AppId   string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppPath string                 `protobuf:"bytes,2,opt,name=app_path,json=appPath,proto3" json:"app_path,omitempty"`
	IsDev   bool                   `protobuf:"varint,3,opt,name=is_dev,json=isDev,proto3" json:"is_dev,omitempty"`
	// Raw contents of the app's schema.star, empty if the app has none.
	AppSchema     []byte `protobuf:"bytes,4,opt,name=app_schema,json=appSchema,proto3" json:"app_schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitAppRequest) Reset() {
	*x = InitAppRequest{}
	mi := &file_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitAppRequest) ProtoMessage() {}

func (x *InitAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitAppRequest.ProtoReflect.Descriptor instead.
func (*InitAppRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *InitAppRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *InitAppRequest) GetAppPath() string {
	if x != nil {
		return x.AppPath
	}
	return ""
}

func (x *InitAppRequest) GetIsDev() bool {
	if x != nil {
		return x.IsDev
	}
	return false
}

func (x *InitAppRequest) GetAppSchema() []byte {
	if x != nil {
		return x.AppSchema
	}
	return nil
}

type InitAppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitAppResponse) Reset() {
	*x = InitAppResponse{}
	mi := &file_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitAppResponse) ProtoMessage() {}

func (x *InitAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitAppResponse.ProtoReflect.Descriptor instead.
func (*InitAppResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *InitAppResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type InitModuleRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Module  string                 `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Account string                 `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"` // "" for the default account
	// Per-account plugin settings from the server config, e.g.
	// [plugin."store.ex#myaccount"]. Secrets are expanded by the server.
	Settings      map[string]*StarValue `protobuf:"bytes,3,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitModuleRequest) Reset() {
	*x = InitModuleRequest{}
	mi := &file_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitModuleRequest) ProtoMessage() {}

func (x *InitModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitModuleRequest.ProtoReflect.Descriptor instead.
func (*InitModuleRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *InitModuleRequest) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *InitModuleRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *InitModuleRequest) GetSettings() map[string]*StarValue {
	if x != nil {
		return x.Settings
	}
	return nil
}

type InitModuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitModuleResponse) Reset() {
	*x = InitModuleResponse{}
	mi := &file_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitModuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitModuleResponse) ProtoMessage() {}

func (x *InitModuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitModuleResponse.ProtoReflect.Descriptor instead.
func (*InitModuleResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *InitModuleResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ThreadState snapshots the request-scoped Starlark thread state a plugin
// function may read.
type ThreadState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserSubject   string                 `protobuf:"bytes,3,opt,name=user_subject,json=userSubject,proto3" json:"user_subject,omitempty"`
	UserEmail     string                 `protobuf:"bytes,4,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	Groups        []string               `protobuf:"bytes,5,rep,name=groups,proto3" json:"groups,omitempty"`
	AppUrl        string                 `protobuf:"bytes,6,opt,name=app_url,json=appUrl,proto3" json:"app_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreadState) Reset() {
	*x = ThreadState{}
	mi := &file_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadState) ProtoMessage() {}

func (x *ThreadState) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadState.ProtoReflect.Descriptor instead.
func (*ThreadState) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *ThreadState) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ThreadState) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ThreadState) GetUserSubject() string {
	if x != nil {
		return x.UserSubject
	}
	return ""
}

func (x *ThreadState) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *ThreadState) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *ThreadState) GetAppUrl() string {
	if x != nil {
		return x.AppUrl
	}
	return ""
}

type Kwarg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         *StarValue             `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kwarg) Reset() {
	*x = Kwarg{}
	mi := &file_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kwarg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kwarg) ProtoMessage() {}

func (x *Kwarg) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kwarg.ProtoReflect.Descriptor instead.
func (*Kwarg) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *Kwarg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Kwarg) GetValue() *StarValue {
	if x != nil {
		return x.Value
	}
	return nil
}

type CallRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Module   string                 `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Account  string                 `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Function string                 `protobuf:"bytes,3,opt,name=function,proto3" json:"function,omitempty"`
	Args     []*StarValue           `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
	Kwargs   []*Kwarg               `protobuf:"bytes,5,rep,name=kwargs,proto3" json:"kwargs,omitempty"` // call-site order preserved
	Thread   *ThreadState           `protobuf:"bytes,6,opt,name=thread,proto3" json:"thread,omitempty"`
	// Session groups the calls of one request: provider-side cross-call state
	// (transactions, cursors) is scoped to it and released by EndSession.
	SessionId     string `protobuf:"bytes,7,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallRequest) Reset() {
	*x = CallRequest{}
	mi := &file_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRequest) ProtoMessage() {}

func (x *CallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallRequest.ProtoReflect.Descriptor instead.
func (*CallRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{19}
}

func (x *CallRequest) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *CallRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *CallRequest) GetFunction() string {
	if x != nil {
		return x.Function
	}
	return ""
}

func (x *CallRequest) GetArgs() []*StarValue {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *CallRequest) GetKwargs() []*Kwarg {
	if x != nil {
		return x.Kwargs
	}
	return nil
}

func (x *CallRequest) GetThread() *ThreadState {
	if x != nil {
		return x.Thread
	}
	return nil
}

func (x *CallRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CallResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Value     *StarValue             `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Error     string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	ErrorCode int64                  `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"` // 0 on success; 1 is the default error code
	// The session's strict deferred-cleanup keys after this call. The server
	// mirrors them as strict cleanup entries so a strict resource still
	// registered at request end fails the request as a leak, matching the
	// strict DeferCleanup contract of builtin plugins.
	StrictKeys    []string `protobuf:"bytes,4,rep,name=strict_keys,json=strictKeys,proto3" json:"strict_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallResponse) Reset() {
	*x = CallResponse{}
	mi := &file_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallResponse) ProtoMessage() {}

func (x *CallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallResponse.ProtoReflect.Descriptor instead.
func (*CallResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{20}
}

func (x *CallResponse) GetValue() *StarValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *CallResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CallResponse) GetErrorCode() int64 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *CallResponse) GetStrictKeys() []string {
	if x != nil {
		return x.StrictKeys
	}
	return nil
}

type CursorNextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CursorId      string                 `protobuf:"bytes,2,opt,name=cursor_id,json=cursorId,proto3" json:"cursor_id,omitempty"`
	MaxItems      int32                  `protobuf:"varint,3,opt,name=max_items,json=maxItems,proto3" json:"max_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CursorNextRequest) Reset() {
	*x = CursorNextRequest{}
	mi := &file_plugin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CursorNextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CursorNextRequest) ProtoMessage() {}

func (x *CursorNextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CursorNextRequest.ProtoReflect.Descriptor instead.
func (*CursorNextRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{21}
}

func (x *CursorNextRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CursorNextRequest) GetCursorId() string {
	if x != nil {
		return x.CursorId
	}
	return ""
}

func (x *CursorNextRequest) GetMaxItems() int32 {
	if x != nil {
		return x.MaxItems
	}
	return 0
}

type CursorNextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*StarValue           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Done          bool                   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"` // no more items; the provider has closed the cursor
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CursorNextResponse) Reset() {
	*x = CursorNextResponse{}
	mi := &file_plugin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CursorNextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CursorNextResponse) ProtoMessage() {}

func (x *CursorNextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CursorNextResponse.ProtoReflect.Descriptor instead.
func (*CursorNextResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{22}
}

func (x *CursorNextResponse) GetItems() []*StarValue {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CursorNextResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *CursorNextResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CursorCloseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CursorId      string                 `protobuf:"bytes,2,opt,name=cursor_id,json=cursorId,proto3" json:"cursor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CursorCloseRequest) Reset() {
	*x = CursorCloseRequest{}
	mi := &file_plugin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CursorCloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CursorCloseRequest) ProtoMessage() {}

func (x *CursorCloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CursorCloseRequest.ProtoReflect.Descriptor instead.
func (*CursorCloseRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{23}
}

func (x *CursorCloseRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CursorCloseRequest) GetCursorId() string {
	if x != nil {
		return x.CursorId
	}
	return ""
}

type CursorCloseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CursorCloseResponse) Reset() {
	*x = CursorCloseResponse{}
	mi := &file_plugin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CursorCloseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CursorCloseResponse) ProtoMessage() {}

func (x *CursorCloseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CursorCloseResponse.ProtoReflect.Descriptor instead.
func (*CursorCloseResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{24}
}

func (x *CursorCloseResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type EndSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Failed        bool                   `protobuf:"varint,2,opt,name=failed,proto3" json:"failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndSessionRequest) Reset() {
	*x = EndSessionRequest{}
	mi := &file_plugin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSessionRequest) ProtoMessage() {}

func (x *EndSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSessionRequest.ProtoReflect.Descriptor instead.
func (*EndSessionRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{25}
}

func (x *EndSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EndSessionRequest) GetFailed() bool {
	if x != nil {
		return x.Failed
	}
	return false
}

type EndSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"` // deferred cleanup failures, for server-side logging
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndSessionResponse) Reset() {
	*x = EndSessionResponse{}
	mi := &file_plugin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSessionResponse) ProtoMessage() {}

func (x *EndSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSessionResponse.ProtoReflect.Descriptor instead.
func (*EndSessionResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{26}
}

func (x *EndSessionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CheckHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckHealthRequest) Reset() {
	*x = CheckHealthRequest{}
	mi := &file_plugin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHealthRequest) ProtoMessage() {}

func (x *CheckHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHealthRequest.ProtoReflect.Descriptor instead.
func (*CheckHealthRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{27}
}

type CheckHealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckHealthResponse) Reset() {
	*x = CheckHealthResponse{}
	mi := &file_plugin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHealthResponse) ProtoMessage() {}

func (x *CheckHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHealthResponse.ProtoReflect.Descriptor instead.
func (*CheckHealthResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{28}
}

func (x *CheckHealthResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\x11openrun.plugin.v1\"\x9e\x05\n" +
	"\tStarValue\x12\x14\n" +
	"\x04none\x18\x01 \x01(\bH\x00R\x04none\x12\x14\n" +
	"\x04bool\x18\x02 \x01(\bH\x00R\x04bool\x12\x12\n" +
	"\x03int\x18\x03 \x01(\x03H\x00R\x03int\x123\n" +
	"\x06bigint\x18\x04 \x01(\v2\x19.openrun.plugin.v1.BigIntH\x00R\x06bigint\x12\x16\n" +
	"\x05float\x18\x05 \x01(\x01H\x00R\x05float\x12\x12\n" +
	"\x03str\x18\x06 \x01(\tH\x00R\x03str\x12\x16\n" +
	"\x05bytes\x18\a \x01(\fH\x00R\x05bytes\x122\n" +
	"\x04list\x18\b \x01(\v2\x1c.openrun.plugin.v1.ValueListH\x00R\x04list\x124\n" +
	"\x05tuple\x18\t \x01(\v2\x1c.openrun.plugin.v1.ValueListH\x00R\x05tuple\x120\n" +
	"\x03set\x18\n" +
	" \x01(\v2\x1c.openrun.plugin.v1.ValueListH\x00R\x03set\x121\n" +
	"\x04dict\x18\v \x01(\v2\x1b.openrun.plugin.v1.StarDictH\x00R\x04dict\x128\n" +
	"\x06struct\x18\f \x01(\v2\x1e.openrun.plugin.v1.TypedStructH\x00R\x06struct\x12(\n" +
	"\x0ftime_unix_nanos\x18\r \x01(\x03H\x00R\rtimeUnixNanos\x123\n" +
	"\x06cursor\x18\x0e \x01(\v2\x19.openrun.plugin.v1.CursorH\x00R\x06cursor\x120\n" +
	"\x05thunk\x18\x0f \x01(\v2\x18.openrun.plugin.v1.ThunkH\x00R\x05thunk\x126\n" +
	"\afuncref\x18\x10 \x01(\v2\x1a.openrun.plugin.v1.FuncRefH\x00R\afuncrefB\x06\n" +
	"\x04kind\"W\n" +
	"\aFuncRef\x12\x1a\n" +
	"\bfunction\x18\x01 \x01(\tR\bfunction\x120\n" +
	"\x04args\x18\x02 \x03(\v2\x1c.openrun.plugin.v1.StarValueR\x04args\"e\n" +
	"\x05Thunk\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.openrun.plugin.v1.StarValueR\x05value\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"6\n" +
	"\x06BigInt\x12\x1a\n" +
	"\bnegative\x18\x01 \x01(\bR\bnegative\x12\x10\n" +
	"\x03abs\x18\x02 \x01(\fR\x03abs\"A\n" +
	"\tValueList\x124\n" +
	"\x06values\x18\x01 \x03(\v2\x1c.openrun.plugin.v1.StarValueR\x06values\"B\n" +
	"\bStarDict\x126\n" +
	"\aentries\x18\x01 \x03(\v2\x1c.openrun.plugin.v1.StarEntryR\aentries\"o\n" +
	"\tStarEntry\x12.\n" +
	"\x03key\x18\x01 \x01(\v2\x1c.openrun.plugin.v1.StarValueR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.openrun.plugin.v1.StarValueR\x05value\"_\n" +
	"\vTypedStruct\x12\x1b\n" +
	"\ttype_name\x18\x01 \x01(\tR\btypeName\x123\n" +
	"\x06fields\x18\x02 \x01(\v2\x1b.openrun.plugin.v1.StarDictR\x06fields\"u\n" +
	"\x06Cursor\x12\x1b\n" +
	"\tcursor_id\x18\x01 \x01(\tR\bcursorId\x12\x1b\n" +
	"\ttype_name\x18\x02 \x01(\tR\btypeName\x12\x19\n" +
	"\bleak_key\x18\x03 \x01(\tR\aleakKey\x12\x16\n" +
	"\x06stream\x18\x04 \x01(\bR\x06stream\"\x11\n" +
	"\x0fDescribeRequest\"z\n" +
	"\x10DescribeResponse\x12)\n" +
	"\x10provider_version\x18\x01 \x01(\tR\x0fproviderVersion\x12;\n" +
	"\amodules\x18\x02 \x03(\v2!.openrun.plugin.v1.ModuleManifestR\amodules\"\x93\x02\n" +
	"\x0eModuleManifest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12A\n" +
	"\tfunctions\x18\x02 \x03(\v2#.openrun.plugin.v1.FunctionManifestR\tfunctions\x12N\n" +
	"\tconstants\x18\x03 \x03(\v20.openrun.plugin.v1.ModuleManifest.ConstantsEntryR\tconstants\x1aZ\n" +
	"\x0eConstantsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.openrun.plugin.v1.StarValueR\x05value:\x028\x01\"?\n" +
	"\x10FunctionManifest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\ais_read\x18\x02 \x01(\bR\x06isRead\"x\n" +
	"\x0eInitAppRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x19\n" +
	"\bapp_path\x18\x02 \x01(\tR\aappPath\x12\x15\n" +
	"\x06is_dev\x18\x03 \x01(\bR\x05isDev\x12\x1d\n" +
	"\n" +
	"app_schema\x18\x04 \x01(\fR\tappSchema\"'\n" +
	"\x0fInitAppResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\xf0\x01\n" +
	"\x11InitModuleRequest\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\x12\x18\n" +
	"\aaccount\x18\x02 \x01(\tR\aaccount\x12N\n" +
	"\bsettings\x18\x03 \x03(\v22.openrun.plugin.v1.InitModuleRequest.SettingsEntryR\bsettings\x1aY\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.openrun.plugin.v1.StarValueR\x05value:\x028\x01\"*\n" +
	"\x12InitModuleResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\xb8\x01\n" +
	"\vThreadState\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\fuser_subject\x18\x03 \x01(\tR\vuserSubject\x12\x1d\n" +
	"\n" +
	"user_email\x18\x04 \x01(\tR\tuserEmail\x12\x16\n" +
	"\x06groups\x18\x05 \x03(\tR\x06groups\x12\x17\n" +
	"\aapp_url\x18\x06 \x01(\tR\x06appUrl\"O\n" +
	"\x05Kwarg\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.openrun.plugin.v1.StarValueR\x05value\"\x96\x02\n" +
	"\vCallRequest\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\x12\x18\n" +
	"\aaccount\x18\x02 \x01(\tR\aaccount\x12\x1a\n" +
	"\bfunction\x18\x03 \x01(\tR\bfunction\x120\n" +
	"\x04args\x18\x04 \x03(\v2\x1c.openrun.plugin.v1.StarValueR\x04args\x120\n" +
	"\x06kwargs\x18\x05 \x03(\v2\x18.openrun.plugin.v1.KwargR\x06kwargs\x126\n" +
	"\x06thread\x18\x06 \x01(\v2\x1e.openrun.plugin.v1.ThreadStateR\x06thread\x12\x1d\n" +
	"\n" +
	"session_id\x18\a \x01(\tR\tsessionId\"\x98\x01\n" +
	"\fCallResponse\x122\n" +
	"\x05value\x18\x01 \x01(\v2\x1c.openrun.plugin.v1.StarValueR\x05value\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\x03R\terrorCode\x12\x1f\n" +
	"\vstrict_keys\x18\x04 \x03(\tR\n" +
	"strictKeys\"l\n" +
	"\x11CursorNextRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tcursor_id\x18\x02 \x01(\tR\bcursorId\x12\x1b\n" +
	"\tmax_items\x18\x03 \x01(\x05R\bmaxItems\"r\n" +
	"\x12CursorNextResponse\x122\n" +
	"\x05items\x18\x01 \x03(\v2\x1c.openrun.plugin.v1.StarValueR\x05items\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"P\n" +
	"\x12CursorCloseRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tcursor_id\x18\x02 \x01(\tR\bcursorId\"+\n" +
	"\x13CursorCloseResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"J\n" +
	"\x11EndSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06failed\x18\x02 \x01(\bR\x06failed\"*\n" +
	"\x12EndSessionResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\x14\n" +
	"\x12CheckHealthRequest\"+\n" +
	"\x13CheckHealthResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error2\xcd\x05\n" +
	"\x0ePluginProvider\x12S\n" +
	"\bDescribe\x12\".openrun.plugin.v1.DescribeRequest\x1a#.openrun.plugin.v1.DescribeResponse\x12P\n" +
	"\aInitApp\x12!.openrun.plugin.v1.InitAppRequest\x1a\".openrun.plugin.v1.InitAppResponse\x12Y\n" +
	"\n" +
	"InitModule\x12$.openrun.plugin.v1.InitModuleRequest\x1a%.openrun.plugin.v1.InitModuleResponse\x12G\n" +
	"\x04Call\x12\x1e.openrun.plugin.v1.CallRequest\x1a\x1f.openrun.plugin.v1.CallResponse\x12Y\n" +
	"\n" +
	"CursorNext\x12$.openrun.plugin.v1.CursorNextRequest\x1a%.openrun.plugin.v1.CursorNextResponse\x12\\\n" +
	"\vCursorClose\x12%.openrun.plugin.v1.CursorCloseRequest\x1a&.openrun.plugin.v1.CursorCloseResponse\x12Y\n" +
	"\n" +
	"EndSession\x12$.openrun.plugin.v1.EndSessionRequest\x1a%.openrun.plugin.v1.EndSessionResponse\x12\\\n" +
	"\vCheckHealth\x12%.openrun.plugin.v1.CheckHealthRequest\x1a&.openrun.plugin.v1.CheckHealthResponseB0Z.github.com/openrundev/openrun/pkg/plugin/protob\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_plugin_proto_goTypes = []any{
	(*StarValue)(nil),           // 0: openrun.plugin.v1.StarValue
	(*FuncRef)(nil),             // 1: openrun.plugin.v1.FuncRef
	(*Thunk)(nil),               // 2: openrun.plugin.v1.Thunk
	(*BigInt)(nil),              // 3: openrun.plugin.v1.BigInt
	(*ValueList)(nil),           // 4: openrun.plugin.v1.ValueList
	(*StarDict)(nil),            // 5: openrun.plugin.v1.StarDict
	(*StarEntry)(nil),           // 6: openrun.plugin.v1.StarEntry
	(*TypedStruct)(nil),         // 7: openrun.plugin.v1.TypedStruct
	(*Cursor)(nil),              // 8: openrun.plugin.v1.Cursor
	(*DescribeRequest)(nil),     // 9: openrun.plugin.v1.DescribeRequest
	(*DescribeResponse)(nil),    // 10: openrun.plugin.v1.DescribeResponse
	(*ModuleManifest)(nil),      // 11: openrun.plugin.v1.ModuleManifest
	(*FunctionManifest)(nil),    // 12: openrun.plugin.v1.FunctionManifest
	(*InitAppRequest)(nil),      // 13: openrun.plugin.v1.InitAppRequest
	(*InitAppResponse)(nil),     // 14: openrun.plugin.v1.InitAppResponse
	(*InitModuleRequest)(nil),   // 15: openrun.plugin.v1.InitModuleRequest
	(*InitModuleResponse)(nil),  // 16: openrun.plugin.v1.InitModuleResponse
	(*ThreadState)(nil),         // 17: openrun.plugin.v1.ThreadState
	(*Kwarg)(nil),               // 18: openrun.plugin.v1.Kwarg
	(*CallRequest)(nil),         // 19: openrun.plugin.v1.CallRequest
	(*CallResponse)(nil),        // 20: openrun.plugin.v1.CallResponse
	(*CursorNextRequest)(nil),   // 21: openrun.plugin.v1.CursorNextRequest
	(*CursorNextResponse)(nil),  // 22: openrun.plugin.v1.CursorNextResponse
	(*CursorCloseRequest)(nil),  // 23: openrun.plugin.v1.CursorCloseRequest
	(*CursorCloseResponse)(nil), // 24: openrun.plugin.v1.CursorCloseResponse
	(*EndSessionRequest)(nil),   // 25: openrun.plugin.v1.EndSessionRequest
	(*EndSessionResponse)(nil),  // 26: openrun.plugin.v1.EndSessionResponse
	(*CheckHealthRequest)(nil),  // 27: openrun.plugin.v1.CheckHealthRequest
	(*CheckHealthResponse)(nil), // 28: openrun.plugin.v1.CheckHealthResponse
	nil,                         // 29: openrun.plugin.v1.ModuleManifest.ConstantsEntry
	nil,                         // 30: openrun.plugin.v1.InitModuleRequest.SettingsEntry
}
var file_plugin_proto_depIdxs = []int32{
	3,  // 0: openrun.plugin.v1.StarValue.bigint:type_name -> openrun.plugin.v1.BigInt
	4,  // 1: openrun.plugin.v1.StarValue.list:type_name -> openrun.plugin.v1.ValueList
	4,  // 2: openrun.plugin.v1.StarValue.tuple:type_name -> openrun.plugin.v1.ValueList
	4,  // 3: openrun.plugin.v1.StarValue.set:type_name -> openrun.plugin.v1.ValueList
	5,  // 4: openrun.plugin.v1.StarValue.dict:type_name -> openrun.plugin.v1.StarDict
	7,  // 5: openrun.plugin.v1.StarValue.struct:type_name -> openrun.plugin.v1.TypedStruct
	8,  // 6: openrun.plugin.v1.StarValue.cursor:type_name -> openrun.plugin.v1.Cursor
	2,  // 7: openrun.plugin.v1.StarValue.thunk:type_name -> openrun.plugin.v1.Thunk
	1,  // 8: openrun.plugin.v1.StarValue.funcref:type_name -> openrun.plugin.v1.FuncRef
	0,  // 9: openrun.plugin.v1.FuncRef.args:type_name -> openrun.plugin.v1.StarValue
	0,  // 10: openrun.plugin.v1.Thunk.value:type_name -> openrun.plugin.v1.StarValue
	0,  // 11: openrun.plugin.v1.ValueList.values:type_name -> openrun.plugin.v1.StarValue
	6,  // 12: openrun.plugin.v1.StarDict.entries:type_name -> openrun.plugin.v1.StarEntry
	0,  // 13: openrun.plugin.v1.StarEntry.key:type_name -> openrun.plugin.v1.StarValue
	0,  // 14: openrun.plugin.v1.StarEntry.value:type_name -> openrun.plugin.v1.StarValue
	5,  // 15: openrun.plugin.v1.TypedStruct.fields:type_name -> openrun.plugin.v1.StarDict
	11, // 16: openrun.plugin.v1.DescribeResponse.modules:type_name -> openrun.plugin.v1.ModuleManifest
	12, // 17: openrun.plugin.v1.ModuleManifest.functions:type_name -> openrun.plugin.v1.FunctionManifest
	29, // 18: openrun.plugin.v1.ModuleManifest.constants:type_name -> openrun.plugin.v1.ModuleManifest.ConstantsEntry
	30, // 19: openrun.plugin.v1.InitModuleRequest.settings:type_name -> openrun.plugin.v1.InitModuleRequest.SettingsEntry
	0,  // 20: openrun.plugin.v1.Kwarg.value:type_name -> openrun.plugin.v1.StarValue
	0,  // 21: openrun.plugin.v1.CallRequest.args:type_name -> openrun.plugin.v1.StarValue
	18, // 22: openrun.plugin.v1.CallRequest.kwargs:type_name -> openrun.plugin.v1.Kwarg
	17, // 23: openrun.plugin.v1.CallRequest.thread:type_name -> openrun.plugin.v1.ThreadState
	0,  // 24: openrun.plugin.v1.CallResponse.value:type_name -> openrun.plugin.v1.StarValue
	0,  // 25: openrun.plugin.v1.CursorNextResponse.items:type_name -> openrun.plugin.v1.StarValue
	0,  // 26: openrun.plugin.v1.ModuleManifest.ConstantsEntry.value:type_name -> openrun.plugin.v1.StarValue
	0,  // 27: openrun.plugin.v1.InitModuleRequest.SettingsEntry.value:type_name -> openrun.plugin.v1.StarValue
	9,  // 28: openrun.plugin.v1.PluginProvider.Describe:input_type -> openrun.plugin.v1.DescribeRequest
	13, // 29: openrun.plugin.v1.PluginProvider.InitApp:input_type -> openrun.plugin.v1.InitAppRequest
	15, // 30: openrun.plugin.v1.PluginProvider.InitModule:input_type -> openrun.plugin.v1.InitModuleRequest
	19, // 31: openrun.plugin.v1.PluginProvider.Call:input_type -> openrun.plugin.v1.CallRequest
	21, // 32: openrun.plugin.v1.PluginProvider.CursorNext:input_type -> openrun.plugin.v1.CursorNextRequest
	23, // 33: openrun.plugin.v1.PluginProvider.CursorClose:input_type -> openrun.plugin.v1.CursorCloseRequest
	25, // 34: openrun.plugin.v1.PluginProvider.EndSession:input_type -> openrun.plugin.v1.EndSessionRequest
	27, // 35: openrun.plugin.v1.PluginProvider.CheckHealth:input_type -> openrun.plugin.v1.CheckHealthRequest
	10, // 36: openrun.plugin.v1.PluginProvider.Describe:output_type -> openrun.plugin.v1.DescribeResponse
	14, // 37: openrun.plugin.v1.PluginProvider.InitApp:output_type -> openrun.plugin.v1.InitAppResponse
	16, // 38: openrun.plugin.v1.PluginProvider.InitModule:output_type -> openrun.plugin.v1.InitModuleResponse
	20, // 39: openrun.plugin.v1.PluginProvider.Call:output_type -> openrun.plugin.v1.CallResponse
	22, // 40: openrun.plugin.v1.PluginProvider.CursorNext:output_type -> openrun.plugin.v1.CursorNextResponse
	24, // 41: openrun.plugin.v1.PluginProvider.CursorClose:output_type -> openrun.plugin.v1.CursorCloseResponse
	26, // 42: openrun.plugin.v1.PluginProvider.EndSession:output_type -> openrun.plugin.v1.EndSessionResponse
	28, // 43: openrun.plugin.v1.PluginProvider.CheckHealth:output_type -> openrun.plugin.v1.CheckHealthResponse
	36, // [36:44] is the sub-list for method output_type
	28, // [28:36] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	file_plugin_proto_msgTypes[0].OneofWrappers = []any{
		(*StarValue_None)(nil),
		(*StarValue_Bool)(nil),
		(*StarValue_Int)(nil),
		(*StarValue_Bigint)(nil),
		(*StarValue_Float)(nil),
		(*StarValue_Str)(nil),
		(*StarValue_Bytes)(nil),
		(*StarValue_List)(nil),
		(*StarValue_Tuple)(nil),
		(*StarValue_Set)(nil),
		(*StarValue_Dict)(nil),
		(*StarValue_Struct)(nil),
		(*StarValue_TimeUnixNanos)(nil),
		(*StarValue_Cursor)(nil),
		(*StarValue_Thunk)(nil),
		(*StarValue_Funcref)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
