// Copyright (c) ClaceIO, LLC
// SPDX-License-Identifier: Apache-2.0

// Wire contract between the OpenRun server and out-of-process Starlark plugin
// providers (modules loaded in apps with load("name.ex", ...)). This proto is
// the single source of truth for the plugin provider protocol; the server and
// the provider SDK each map it to their own Go types.
//
// Application-level failures are carried in the response `error` field, not as
// gRPC status errors: a plugin call error feeds the app's PluginResponse error
// handling (response.error / error_handler). gRPC status errors are reserved
// for transport failures (provider crash, protocol mismatch); the server kills
// the provider process, fails the request's live sessions, and respawns the
// process on the next request. Plugin calls are never retried automatically.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.4
// source: plugin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginProvider_Describe_FullMethodName    = "/openrun.plugin.v1.PluginProvider/Describe"
	PluginProvider_InitApp_FullMethodName     = "/openrun.plugin.v1.PluginProvider/InitApp"
	PluginProvider_InitModule_FullMethodName  = "/openrun.plugin.v1.PluginProvider/InitModule"
	PluginProvider_Call_FullMethodName        = "/openrun.plugin.v1.PluginProvider/Call"
	PluginProvider_CursorNext_FullMethodName  = "/openrun.plugin.v1.PluginProvider/CursorNext"
	PluginProvider_CursorClose_FullMethodName = "/openrun.plugin.v1.PluginProvider/CursorClose"
	PluginProvider_EndSession_FullMethodName  = "/openrun.plugin.v1.PluginProvider/EndSession"
	PluginProvider_CheckHealth_FullMethodName = "/openrun.plugin.v1.PluginProvider/CheckHealth"
)

// PluginProviderClient is the client API for PluginProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PluginProviderClient interface {
	// Describe reports the modules served by this provider binary: function
	// manifests (used to build the Starlark module at load time without
	// launching a provider process) and module constants. Valid before InitApp.
	Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error)
	// InitApp establishes the app identity for this provider process. The
	// server launches one provider process per app; InitApp is called once,
	// immediately after the handshake. A second call is a protocol error.
	InitApp(ctx context.Context, in *InitAppRequest, opts ...grpc.CallOption) (*InitAppResponse, error)
	// InitModule initializes one (module, account) instance in this process,
	// called lazily before the instance's first Call.
	InitModule(ctx context.Context, in *InitModuleRequest, opts ...grpc.CallOption) (*InitModuleResponse, error)
	// Call invokes one plugin function. The hot path.
	Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallResponse, error)
	// CursorNext fetches the next batch of items from a cursor returned by a
	// previous Call in the same session.
	CursorNext(ctx context.Context, in *CursorNextRequest, opts ...grpc.CallOption) (*CursorNextResponse, error)
	// CursorClose releases a cursor. Closing an unknown cursor or session is
	// not an error (the cursor may have been drained or the session ended).
	CursorClose(ctx context.Context, in *CursorCloseRequest, opts ...grpc.CallOption) (*CursorCloseResponse, error)
	// EndSession releases all state held for a session: remaining deferred
	// cleanups run (open transactions roll back, cursors close) and the session
	// is forgotten. Called by the server when the request handler finishes.
	EndSession(ctx context.Context, in *EndSessionRequest, opts ...grpc.CallOption) (*EndSessionResponse, error)
	// CheckHealth reports whether the provider process is healthy.
	CheckHealth(ctx context.Context, in *CheckHealthRequest, opts ...grpc.CallOption) (*CheckHealthResponse, error)
}

type pluginProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginProviderClient(cc grpc.ClientConnInterface) PluginProviderClient {
	return &pluginProviderClient{cc}
}

func (c *pluginProviderClient) Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeResponse)
	err := c.cc.Invoke(ctx, PluginProvider_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginProviderClient) InitApp(ctx context.Context, in *InitAppRequest, opts ...grpc.CallOption) (*InitAppResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitAppResponse)
	err := c.cc.Invoke(ctx, PluginProvider_InitApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginProviderClient) InitModule(ctx context.Context, in *InitModuleRequest, opts ...grpc.CallOption) (*InitModuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitModuleResponse)
	err := c.cc.Invoke(ctx, PluginProvider_InitModule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginProviderClient) Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallResponse)
	err := c.cc.Invoke(ctx, PluginProvider_Call_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginProviderClient) CursorNext(ctx context.Context, in *CursorNextRequest, opts ...grpc.CallOption) (*CursorNextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CursorNextResponse)
	err := c.cc.Invoke(ctx, PluginProvider_CursorNext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginProviderClient) CursorClose(ctx context.Context, in *CursorCloseRequest, opts ...grpc.CallOption) (*CursorCloseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CursorCloseResponse)
	err := c.cc.Invoke(ctx, PluginProvider_CursorClose_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginProviderClient) EndSession(ctx context.Context, in *EndSessionRequest, opts ...grpc.CallOption) (*EndSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EndSessionResponse)
	err := c.cc.Invoke(ctx, PluginProvider_EndSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginProviderClient) CheckHealth(ctx context.Context, in *CheckHealthRequest, opts ...grpc.CallOption) (*CheckHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckHealthResponse)
	err := c.cc.Invoke(ctx, PluginProvider_CheckHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginProviderServer is the server API for PluginProvider service.
// All implementations must embed UnimplementedPluginProviderServer
// for forward compatibility.
type PluginProviderServer interface {
	// Describe reports the modules served by this provider binary: function
	// manifests (used to build the Starlark module at load time without
	// launching a provider process) and module constants. Valid before InitApp.
	Describe(context.Context, *DescribeRequest) (*DescribeResponse, error)
	// InitApp establishes the app identity for this provider process. The
	// server launches one provider process per app; InitApp is called once,
	// immediately after the handshake. A second call is a protocol error.
	InitApp(context.Context, *InitAppRequest) (*InitAppResponse, error)
	// InitModule initializes one (module, account) instance in this process,
	// called lazily before the instance's first Call.
	InitModule(context.Context, *InitModuleRequest) (*InitModuleResponse, error)
	// Call invokes one plugin function. The hot path.
	Call(context.Context, *CallRequest) (*CallResponse, error)
	// CursorNext fetches the next batch of items from a cursor returned by a
	// previous Call in the same session.
	CursorNext(context.Context, *CursorNextRequest) (*CursorNextResponse, error)
	// CursorClose releases a cursor. Closing an unknown cursor or session is
	// not an error (the cursor may have been drained or the session ended).
	CursorClose(context.Context, *CursorCloseRequest) (*CursorCloseResponse, error)
	// EndSession releases all state held for a session: remaining deferred
	// cleanups run (open transactions roll back, cursors close) and the session
	// is forgotten. Called by the server when the request handler finishes.
	EndSession(context.Context, *EndSessionRequest) (*EndSessionResponse, error)
	// CheckHealth reports whether the provider process is healthy.
	CheckHealth(context.Context, *CheckHealthRequest) (*CheckHealthResponse, error)
	mustEmbedUnimplementedPluginProviderServer()
}

// UnimplementedPluginProviderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginProviderServer struct{}

func (UnimplementedPluginProviderServer) Describe(context.Context, *DescribeRequest) (*DescribeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedPluginProviderServer) InitApp(context.Context, *InitAppRequest) (*InitAppResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitApp not implemented")
}
func (UnimplementedPluginProviderServer) InitModule(context.Context, *InitModuleRequest) (*InitModuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitModule not implemented")
}
func (UnimplementedPluginProviderServer) Call(context.Context, *CallRequest) (*CallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Call not implemented")
}
func (UnimplementedPluginProviderServer) CursorNext(context.Context, *CursorNextRequest) (*CursorNextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CursorNext not implemented")
}
func (UnimplementedPluginProviderServer) CursorClose(context.Context, *CursorCloseRequest) (*CursorCloseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CursorClose not implemented")
}
func (UnimplementedPluginProviderServer) EndSession(context.Context, *EndSessionRequest) (*EndSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EndSession not implemented")
}
func (UnimplementedPluginProviderServer) CheckHealth(context.Context, *CheckHealthRequest) (*CheckHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckHealth not implemented")
}
func (UnimplementedPluginProviderServer) mustEmbedUnimplementedPluginProviderServer() {}
func (UnimplementedPluginProviderServer) testEmbeddedByValue()                        {}

// UnsafePluginProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginProviderServer will
// result in compilation errors.
type UnsafePluginProviderServer interface {
	mustEmbedUnimplementedPluginProviderServer()
}

func RegisterPluginProviderServer(s grpc.ServiceRegistrar, srv PluginProviderServer) {
	// If the following call panics, it indicates UnimplementedPluginProviderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginProvider_ServiceDesc, srv)
}

func _PluginProvider_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginProviderServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginProvider_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginProviderServer).Describe(ctx, req.(*DescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginProvider_InitApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginProviderServer).InitApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginProvider_InitApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginProviderServer).InitApp(ctx, req.(*InitAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginProvider_InitModule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitModuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginProviderServer).InitModule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginProvider_InitModule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginProviderServer).InitModule(ctx, req.(*InitModuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginProvider_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginProviderServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginProvider_Call_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginProviderServer).Call(ctx, req.(*CallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginProvider_CursorNext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CursorNextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginProviderServer).CursorNext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginProvider_CursorNext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginProviderServer).CursorNext(ctx, req.(*CursorNextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginProvider_CursorClose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CursorCloseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginProviderServer).CursorClose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginProvider_CursorClose_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginProviderServer).CursorClose(ctx, req.(*CursorCloseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginProvider_EndSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginProviderServer).EndSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginProvider_EndSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginProviderServer).EndSession(ctx, req.(*EndSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginProvider_CheckHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginProviderServer).CheckHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginProvider_CheckHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginProviderServer).CheckHealth(ctx, req.(*CheckHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginProvider_ServiceDesc is the grpc.ServiceDesc for PluginProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openrun.plugin.v1.PluginProvider",
	HandlerType: (*PluginProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _PluginProvider_Describe_Handler,
		},
		{
			MethodName: "InitApp",
			Handler:    _PluginProvider_InitApp_Handler,
		},
		{
			MethodName: "InitModule",
			Handler:    _PluginProvider_InitModule_Handler,
		},
		{
			MethodName: "Call",
			Handler:    _PluginProvider_Call_Handler,
		},
		{
			MethodName: "CursorNext",
			Handler:    _PluginProvider_CursorNext_Handler,
		},
		{
			MethodName: "CursorClose",
			Handler:    _PluginProvider_CursorClose_Handler,
		},
		{
			MethodName: "EndSession",
			Handler:    _PluginProvider_EndSession_Handler,
		},
		{
			MethodName: "CheckHealth",
			Handler:    _PluginProvider_CheckHealth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}
