// Copyright (c) ClaceIO, LLC
// SPDX-License-Identifier: Apache-2.0

package binding

import (
	"fmt"
	"net/url"
	"strings"
)

// Account map keys common to all bindings. AccountKeyURL is the connection URL
// apps use (with the localhost binding hostname applied when apps run in
// containers); AccountKeyURLDirect keeps the service hostname and is used for
// server-side connections like RunCommand.
const (
	AccountKeyURL       = "url"
	AccountKeyURLDirect = "url_direct"
)

// BindingIDPrefix is the prefix of binding ids as generated by the server.
// Bindings strip it when deriving account object names to stay within
// database identifier length limits.
const BindingIDPrefix = "bnd_"

// NameOptions controls AccountName generation.
type NameOptions struct {
	// MaxLen rejects generated names longer than this; 0 disables the check.
	MaxLen int
	// Uppercase upper-cases the generated name (Oracle-style identifiers).
	Uppercase bool
	// KeepIDPrefix keeps the bnd_ prefix of the binding id instead of
	// stripping it (used where the full id fits the identifier budget).
	KeepIDPrefix bool
}

// AccountName builds an account object name (user/role/schema/login) from the
// binding id: the prod or staging prefix followed by the binding id with its
// bnd_ prefix stripped (unless KeepIDPrefix is set).
func AccountName(prefixProd, prefixStg, bindingId string, isStaging bool, opts NameOptions) (string, error) {
	prefix := prefixProd
	if isStaging {
		prefix = prefixStg
	}
	idCore := bindingId
	if !opts.KeepIDPrefix {
		idCore = strings.TrimPrefix(bindingId, BindingIDPrefix)
	}
	name := prefix + idCore
	if opts.Uppercase {
		name = strings.ToUpper(name)
	}
	if opts.MaxLen > 0 && len(name) > opts.MaxLen {
		return "", fmt.Errorf("computed account name %q exceeds the %d-char identifier limit", name, opts.MaxLen)
	}
	return name, nil
}

// AccountURLs builds the account connection URL pair from the admin URL:
// url has the binding hostname applied (empty or "disable" leaves the host
// unchanged), urlDirect always keeps the service hostname.
func AccountURLs(adminURL, user, password, bindingHostname string) (accountURL, accountDirectURL string, err error) {
	u, err := url.Parse(adminURL)
	if err != nil {
		return "", "", err
	}
	u.User = url.UserPassword(user, password)
	accountDirectURL = u.String()
	SetURLHostname(u, bindingHostname)
	return u.String(), accountDirectURL, nil
}
