// Copyright (c) ClaceIO, LLC
// SPDX-License-Identifier: Apache-2.0

package action

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"fmt"
	"maps"
	"mime"
	"net/http"
	"path"
	"slices"
	"strings"

	"github.com/go-chi/chi/v5"
	"github.com/openrundev/openrun/internal/app/apptype"
	"github.com/openrundev/openrun/internal/app/starlark_type"
	"go.starlark.net/starlark"
)

// API_PATH is the path under the app path which is reserved for the actions
// REST API. Action apps cannot define an action at this path
const API_PATH = "/api"

// The API endpoints use a prefix per operation, with the action path appended.
// Prefixes (instead of suffixes on the action path) keep the endpoints of
// different actions from colliding, an action at /validate does not overlap
// with the validate endpoint of the action at /
const (
	apiActionsPrefix  = "/actions"  // GET returns the param definitions, POST runs the action
	apiSuggestPrefix  = "/suggest"  // POST runs the suggest handler
	apiValidatePrefix = "/validate" // POST runs the handler with dry_run=True
)

// appAPI implements the app level endpoints for the actions REST API. The API
// is mounted at API_PATH under the app path and provides the same functionality
// as the autogenerated form UI, with JSON requests and responses
type appAPI struct {
	appName string
	appPath string
	actions []*Action
}

// BuildAPIRouter creates the router for the actions REST API. Each action gets
// exec/suggest/validate endpoints under the per operation prefixes, in
// addition to the app level action list and OpenAPI spec endpoints
func BuildAPIRouter(appName, appPath string, actions []*Action) *chi.Mux {
	api := &appAPI{
		appName: appName,
		appPath: appPath,
		actions: actions,
	}

	r := chi.NewRouter()
	r.Get("/", api.describe)
	r.Get("/openapi.json", api.openAPISpec)

	for _, act := range actions {
		execPath := path.Join(apiActionsPrefix, act.actionPath)
		r.Get(execPath, act.apiGetSchema)
		r.Post(execPath, act.apiRunAction)
		r.Post(path.Join(apiSuggestPrefix, act.actionPath), act.apiSuggestAction)
		r.Post(path.Join(apiValidatePrefix, act.actionPath), act.apiValidateAction)
	}
	return r
}

func writeJSON(w http.ResponseWriter, code int, v any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(code)
	_ = json.MarshalWrite(w, v) // response is already committed, error cannot be reported
}

func writeJSONError(w http.ResponseWriter, msg string, code int) {
	writeJSON(w, code, map[string]any{"error": msg})
}

func isOptionsParam(name string) bool {
	return strings.HasPrefix(name, OPTIONS_PREFIX) || strings.HasPrefix(name, OPTIONS_PREFIX_UNDERSCORE)
}

func requestHasJSONBody(r *http.Request) bool {
	mediaType, _, err := mime.ParseMediaType(r.Header.Get("Content-Type"))
	if err != nil {
		return false
	}
	return mediaType == "application/json"
}

// buildArgsFromJSON updates args with the values from the JSON request body.
// Values not present in the body retain the app level param values, unlike the
// form UI where all form fields are always submitted. Dropdown params are
// validated against the configured options, same as the form UI
func (a *Action) buildArgsFromJSON(args starlark.StringDict, body map[string]jsontext.Value, options map[string][]string) error {
	visible := map[string]apptype.AppParam{}
	for _, p := range a.params {
		if a.hidden[p.Name] || isOptionsParam(p.Name) {
			continue
		}
		visible[p.Name] = p
	}

	keys := slices.Collect(maps.Keys(body))
	slices.Sort(keys)
	for _, name := range keys {
		param, ok := visible[name]
		if !ok {
			return fmt.Errorf("unknown param %s", name)
		}

		value := body[name]
		if value.Kind() == 'n' {
			continue // null, use the app level param value
		}

		if param.DisplayType == apptype.DisplayTypeFileUpload {
			// File params cannot be set through JSON, the value is a server side
			// file path which the client should not control
			return fmt.Errorf("param %s is a file upload param, submit using multipart/form-data", name)
		}

		newVal, err := jsonValueToParamType(param, value)
		if err != nil {
			return err
		}

		// Dropdown params are strict by default: a non-empty value must be one
		// of the configured options (COMBO display type allows free text)
		if opts := options[name]; len(opts) > 0 && param.DisplayType != apptype.DisplayTypeCombo {
			strVal := newVal.String()
			if s, ok := newVal.(starlark.String); ok {
				strVal = string(s)
			}
			if strVal != "" && !slices.Contains(opts, strVal) {
				return fmt.Errorf("invalid value for %s: must be one of the configured options", name)
			}
		}
		args[name] = newVal
	}
	return nil
}

// jsonValueToParamType converts a raw JSON body value to the starlark value for
// the param type. String values are coerced the same way as form submissions.
// Integers are decoded from the JSON text without going through a float, so
// large values keep their precision and out of range values are rejected
func jsonValueToParamType(param apptype.AppParam, value jsontext.Value) (starlark.Value, error) {
	if value.Kind() == '"' {
		var strValue string
		if err := json.Unmarshal(value, &strValue); err != nil {
			return nil, fmt.Errorf("param %s: %w", param.Name, err)
		}
		return apptype.ParamStringToType(param.Name, param.Type, strValue)
	}

	switch param.Type {
	case starlark_type.STRING:
		return nil, fmt.Errorf("param %s must be a string", param.Name)
	case starlark_type.INT:
		var intValue int64
		if value.Kind() != '0' || json.Unmarshal(value, &intValue) != nil {
			return nil, fmt.Errorf("param %s must be an integer", param.Name)
		}
		return starlark.MakeInt64(intValue), nil
	case starlark_type.BOOLEAN:
		switch value.Kind() {
		case 't':
			return starlark.True, nil
		case 'f':
			return starlark.False, nil
		default:
			return nil, fmt.Errorf("param %s must be a boolean", param.Name)
		}
	case starlark_type.LIST:
		var listValue []any
		if value.Kind() != '[' || json.Unmarshal(value, &listValue) != nil {
			return nil, fmt.Errorf("param %s must be a list", param.Name)
		}
		return starlark_type.FromGo(listValue)
	case starlark_type.DICT:
		var dictValue map[string]any
		if value.Kind() != '{' || json.Unmarshal(value, &dictValue) != nil {
			return nil, fmt.Errorf("param %s must be a dict", param.Name)
		}
		return starlark_type.FromGo(dictValue)
	default:
		var goValue any
		if err := json.Unmarshal(value, &goValue); err != nil {
			return nil, fmt.Errorf("param %s: %w", param.Name, err)
		}
		return starlark_type.FromGo(goValue)
	}
}

// writeAPIRunResponse writes the JSON response for the action run/validate API.
// Param validation errors are reported with a 422 status
func (a *Action) writeAPIRunResponse(w http.ResponseWriter, status string, valuesStr []string,
	valuesMap []map[string]any, paramErrors map[string]any, report string, isValidate bool) {
	errorMsgs := map[string]string{}
	for _, param := range a.params {
		if isOptionsParam(param.Name) {
			continue
		}
		if paramErrors[param.Name] != nil {
			errorMsgs[param.Name] = fmt.Sprintf("%s", paramErrors[param.Name])
		}
	}

	response := map[string]any{
		"status": status,
	}

	code := http.StatusOK
	if len(errorMsgs) > 0 {
		response["param_errors"] = errorMsgs
		code = http.StatusUnprocessableEntity
	} else if !isValidate {
		response["report"] = effectiveReport(report, valuesMap, valuesStr)
		if len(valuesStr) > 0 {
			response["values"] = valuesStr
		} else if valuesMap != nil {
			response["values"] = valuesMap
		} else {
			response["values"] = []any{}
		}
	}

	writeJSON(w, code, response)
}

// effectiveReport resolves the AUTO report type to the actual report type,
// using the same rules as the form UI rendering
func effectiveReport(report string, valuesMap []map[string]any, valuesStr []string) string {
	if report != apptype.AUTO {
		return report
	}
	if len(valuesStr) > 0 || len(valuesMap) == 0 {
		return apptype.TEXT
	}

	for _, v := range valuesMap[0] {
		if v == nil {
			continue
		}
		switch v.(type) {
		case int, string, bool:
		default:
			return apptype.JSON
		}
	}
	return apptype.TABLE
}

// writeAPISuggestResponse writes the JSON response for the suggest API. The
// response params are filtered the same way as the form UI suggest handling
func (a *Action) writeAPISuggestResponse(w http.ResponseWriter, retVal starlark.Value) {
	ret, err := starlark_type.ToGo(retVal)
	if err != nil {
		writeJSONError(w, fmt.Sprintf("error unmarshalling suggest response: %s", err), http.StatusInternalServerError)
		return
	}

	if message, retIsString := ret.(string); retIsString {
		// No suggestions available
		writeJSON(w, http.StatusOK, map[string]any{"status": message})
		return
	}

	retDict := map[string]any{}
	switch retType := ret.(type) {
	case map[string]any:
		retDict = retType
	case map[string]string:
		for k, v := range retType {
			retDict[k] = v
		}
	case map[string]int:
		for k, v := range retType {
			retDict[k] = v
		}
	case map[string]bool:
		for k, v := range retType {
			retDict[k] = v
		}
	case map[string][]string:
		for k, v := range retType {
			retDict[k] = v
		}
	default:
		writeJSONError(w, fmt.Sprintf("invalid suggest response type: %T, expected dict", retType), http.StatusInternalServerError)
		return
	}

	paramMap := map[string]bool{}
	for _, p := range a.params {
		paramMap[p.Name] = true
	}

	params := map[string]any{}
	for key, value := range retDict {
		if !paramMap[key] || isOptionsParam(key) {
			a.Info().Msgf("ignoring suggest response for param: %s", key)
			continue
		}
		params[key] = value
	}

	writeJSON(w, http.StatusOK, map[string]any{"status": "Suggesting values", "params": params})
}

type apiActionInfo struct {
	Name         string `json:"name"`
	Description  string `json:"description,omitempty"`
	Path         string `json:"path"`
	ValidatePath string `json:"validate_path"`
	SuggestPath  string `json:"suggest_path,omitempty"`
	UIPath       string `json:"ui_path"`
	Suggest      bool   `json:"suggest"`
	Authorized   bool   `json:"authorized"`
}

// apiPath returns the full API path for an action under the given operation prefix
func (api *appAPI) apiPath(prefix string, act *Action) string {
	return path.Join(api.appPath, API_PATH, prefix, act.actionPath)
}

// authorized reports whether the current user has access to the action, as
// per the action's permit list
func (api *appAPI) authorized(r *http.Request, act *Action) (bool, error) {
	if act.rbacApi == nil || len(act.permit) == 0 {
		return true, nil
	}
	return act.rbacApi.AuthorizeAny(r.Context(), act.permit)
}

// describe lists the actions available in the app, with their API paths
func (api *appAPI) describe(w http.ResponseWriter, r *http.Request) {
	infos := make([]apiActionInfo, 0, len(api.actions))
	for _, act := range api.actions {
		authorized, err := api.authorized(r, act)
		if err != nil {
			writeJSONError(w, err.Error(), http.StatusInternalServerError)
			return
		}

		uiPath := act.pagePath
		if uiPath == "" {
			uiPath = "/"
		}
		info := apiActionInfo{
			Name:         act.name,
			Description:  act.description,
			Path:         api.apiPath(apiActionsPrefix, act),
			ValidatePath: api.apiPath(apiValidatePrefix, act),
			UIPath:       uiPath,
			Suggest:      act.suggest != nil,
			Authorized:   authorized,
		}
		if act.suggest != nil {
			info.SuggestPath = api.apiPath(apiSuggestPrefix, act)
		}
		infos = append(infos, info)
	}

	writeJSON(w, http.StatusOK, map[string]any{"app": api.appName, "actions": infos})
}

type apiParamInfo struct {
	Name        string   `json:"name"`
	Type        string   `json:"type"`
	Description string   `json:"description,omitempty"`
	Default     any      `json:"default,omitempty"`
	Required    bool     `json:"required"`
	DisplayType string   `json:"display_type,omitempty"`
	Options     []string `json:"options,omitempty"`
}

// paramDefault returns the app level value for a param, converted to its
// native type. The string value is returned if the conversion fails
func (a *Action) paramDefault(p apptype.AppParam) any {
	valueStr, ok := a.paramValuesStr[p.Name]
	if !ok {
		return nil
	}
	value, err := apptype.ParamStringToType(p.Name, p.Type, valueStr)
	if err != nil {
		return valueStr
	}
	goValue, err := starlark_type.ToGo(value)
	if err != nil {
		return valueStr
	}
	return goValue
}

// apiGetSchema returns the param definitions for an action
func (a *Action) apiGetSchema(w http.ResponseWriter, r *http.Request) {
	if !a.authorizeAction(w, r, true) {
		return
	}

	options, err := a.paramOptions()
	if err != nil {
		writeJSONError(w, err.Error(), http.StatusInternalServerError)
		return
	}

	params := make([]apiParamInfo, 0, len(a.params))
	for _, p := range a.params {
		if isOptionsParam(p.Name) || a.hidden[p.Name] {
			continue
		}
		params = append(params, apiParamInfo{
			Name:        p.Name,
			Type:        string(p.Type),
			Description: p.Description,
			Default:     a.paramDefault(p),
			Required:    p.Required,
			DisplayType: string(p.DisplayType),
			Options:     options[p.Name],
		})
	}

	writeJSON(w, http.StatusOK, map[string]any{
		"name":        a.name,
		"description": a.description,
		"params":      params,
		"suggest":     a.suggest != nil,
	})
}

// paramJSONSchema returns the OpenAPI schema for a param
func paramJSONSchema(p apptype.AppParam, options []string, defaultVal any) map[string]any {
	schema := map[string]any{}
	switch p.Type {
	case starlark_type.INT:
		schema["type"] = "integer"
	case starlark_type.FLOAT:
		schema["type"] = "number"
	case starlark_type.BOOLEAN:
		schema["type"] = "boolean"
	case starlark_type.LIST:
		schema["type"] = "array"
		schema["items"] = map[string]any{} // list elements can be of any type
	case starlark_type.DICT:
		schema["type"] = "object"
	case starlark_type.DATETIME:
		schema["type"] = "string"
		schema["format"] = "date-time"
	default:
		schema["type"] = "string"
	}

	description := p.Description
	if p.DisplayType == apptype.DisplayTypeFileUpload {
		description = strings.TrimSpace(description + " (file upload param, submit using multipart/form-data)")
	}
	if description != "" {
		schema["description"] = description
	}
	if len(options) > 0 {
		if p.DisplayType == apptype.DisplayTypeCombo {
			// COMBO allows free text, the options are suggestions only. OpenAPI
			// 3.0 schemas support a single example, the full list is in an extension
			schema["example"] = options[0]
			schema["x-options"] = options
		} else {
			schema["enum"] = options
		}
	}
	if defaultVal != nil {
		schema["default"] = defaultVal
	}
	return schema
}

// operationNames returns a unique OpenAPI operationId name for each action,
// derived from the action path. Path separators are replaced with underscores,
// so different paths can map to the same name (/a/b and /a_b, or / and /root).
// Colliding names get a numeric suffix, chosen so it does not clash with the
// name of any other action either
func operationNames(actions []*Action) map[*Action]string {
	baseNames := make([]string, len(actions))
	reserved := map[string]bool{}
	for i, act := range actions {
		name := strings.Trim(act.actionPath, "/")
		name = strings.ReplaceAll(name, "/", "_")
		if name == "" {
			name = "root"
		}
		baseNames[i] = name
		reserved[name] = true
	}

	names := make(map[*Action]string, len(actions))
	used := map[string]bool{}
	for i, act := range actions {
		name := baseNames[i]
		if used[name] {
			for suffix := 2; ; suffix++ {
				candidate := fmt.Sprintf("%s_%d", name, suffix)
				if !used[candidate] && !reserved[candidate] {
					name = candidate
					break
				}
			}
		}
		used[name] = true
		names[act] = name
	}
	return names
}

// operationId returns the OpenAPI operationId for an operation on an action
func operationId(op string, name string) string {
	return op + "_" + name
}

// openAPISpec generates the OpenAPI 3.0 spec for the app actions. Only the
// actions the current user is authorized for are included, the param
// definitions and defaults of restricted actions are not disclosed
func (api *appAPI) openAPISpec(w http.ResponseWriter, r *http.Request) {
	resultResponse := map[string]any{
		"description": "Action result",
		"content": map[string]any{
			"application/json": map[string]any{
				"schema": map[string]any{"$ref": "#/components/schemas/ActionResult"},
			},
		},
	}
	errorContent := map[string]any{
		"application/json": map[string]any{
			"schema": map[string]any{"$ref": "#/components/schemas/Error"},
		},
	}
	execResponses := map[string]any{
		"200": resultResponse,
		"400": map[string]any{"description": "Invalid request", "content": errorContent},
		"422": map[string]any{
			"description": "Param validation errors",
			"content": map[string]any{
				"application/json": map[string]any{
					"schema": map[string]any{"$ref": "#/components/schemas/ActionResult"},
				},
			},
		},
		"500": map[string]any{"description": "Action failed", "content": errorContent},
	}

	names := operationNames(api.actions)
	paths := map[string]any{}
	for _, act := range api.actions {
		authorized, err := api.authorized(r, act)
		if err != nil {
			writeJSONError(w, err.Error(), http.StatusInternalServerError)
			return
		}
		if !authorized {
			continue
		}

		options, err := act.paramOptions()
		if err != nil {
			writeJSONError(w, err.Error(), http.StatusInternalServerError)
			return
		}

		properties := map[string]any{}
		for _, p := range act.params {
			if isOptionsParam(p.Name) || act.hidden[p.Name] {
				continue
			}
			properties[p.Name] = paramJSONSchema(p, options[p.Name], act.paramDefault(p))
		}

		requestBody := map[string]any{
			"content": map[string]any{
				"application/json": map[string]any{
					"schema": map[string]any{"type": "object", "properties": properties},
				},
			},
		}

		paths[api.apiPath(apiActionsPrefix, act)] = map[string]any{
			"get": map[string]any{
				"operationId": operationId("schema", names[act]),
				"summary":     "Get the param definitions for " + act.name,
				"responses": map[string]any{
					"200": map[string]any{"description": "Action param definitions"},
				},
			},
			"post": map[string]any{
				"operationId": operationId("run", names[act]),
				"summary":     act.name,
				"description": act.description,
				"requestBody": requestBody,
				"responses":   execResponses,
			},
		}
		paths[api.apiPath(apiValidatePrefix, act)] = map[string]any{
			"post": map[string]any{
				"operationId": operationId("validate", names[act]),
				"summary":     "Validate the params for " + act.name,
				"requestBody": requestBody,
				"responses":   execResponses,
			},
		}
		if act.suggest != nil {
			paths[api.apiPath(apiSuggestPrefix, act)] = map[string]any{
				"post": map[string]any{
					"operationId": operationId("suggest", names[act]),
					"summary":     "Suggest param values for " + act.name,
					"requestBody": requestBody,
					"responses":   execResponses,
				},
			}
		}
	}

	spec := map[string]any{
		"openapi": "3.0.3",
		"info": map[string]any{
			"title":   api.appName,
			"version": "1.0.0",
		},
		"paths": paths,
		"components": map[string]any{
			"schemas": map[string]any{
				"ActionResult": map[string]any{
					"type": "object",
					"properties": map[string]any{
						"status": map[string]any{"type": "string"},
						"report": map[string]any{"type": "string"},
						"values": map[string]any{"type": "array", "items": map[string]any{}},
						"param_errors": map[string]any{
							"type":                 "object",
							"additionalProperties": map[string]any{"type": "string"},
						},
					},
				},
				"Error": map[string]any{
					"type": "object",
					"properties": map[string]any{
						"error": map[string]any{"type": "string"},
					},
				},
			},
		},
	}

	writeJSON(w, http.StatusOK, spec)
}
