// Copyright (c) ClaceIO, LLC
// SPDX-License-Identifier: Apache-2.0

package action

import (
	"context"
	"encoding/json/jsontext"
	"encoding/json/v2"
	"fmt"
	"maps"
	"mime"
	"net/http"
	"path"
	"slices"
	"strconv"
	"strings"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/openrundev/openrun/internal/app/apptype"
	"github.com/openrundev/openrun/internal/app/starlark_type"
	"github.com/openrundev/openrun/internal/types"
	"go.starlark.net/starlark"
)

// API_PATH is the path under the app path which is reserved for the actions
// REST API. Action apps cannot define an action at this path
const API_PATH = "/api"

// The API endpoints use a prefix per operation, with the action path appended.
// Prefixes (instead of suffixes on the action path) keep the endpoints of
// different actions from colliding, an action at /validate does not overlap
// with the validate endpoint of the action at /
const (
	apiActionsPrefix  = "/actions"  // GET returns the param definitions, POST runs the action
	apiSuggestPrefix  = "/suggest"  // POST runs the suggest handler
	apiValidatePrefix = "/validate" // POST runs the handler with dry_run=True
	apiRunsPrefix     = "/runs"     // async runs: list, get, output, cancel
)

// appAPI implements the app level endpoints for the actions REST API. The API
// is mounted at API_PATH under the app path and provides the same functionality
// as the autogenerated form UI, with JSON requests and responses
type appAPI struct {
	appName string
	appPath string
	actions []*Action
}

// BuildAPIRouter creates the router for the actions REST API. Each action gets
// exec/suggest/validate endpoints under the per operation prefixes, in
// addition to the app level action list and OpenAPI spec endpoints
func BuildAPIRouter(appName, appPath string, actions []*Action) *chi.Mux {
	api := &appAPI{
		appName: appName,
		appPath: appPath,
		actions: actions,
	}

	r := chi.NewRouter()
	r.Get("/", api.describe)
	r.Get("/openapi.json", api.openAPISpec)

	for _, act := range actions {
		execPath := path.Join(apiActionsPrefix, act.actionPath)
		r.Get(execPath, act.apiGetSchema)
		r.Post(execPath, act.apiRunAction)
		r.Post(path.Join(apiSuggestPrefix, act.actionPath), act.apiSuggestAction)
		r.Post(path.Join(apiValidatePrefix, act.actionPath), act.apiValidateAction)
	}
	hasAsync := false
	for _, act := range actions {
		hasAsync = hasAsync || act.IsAsync()
	}
	if hasAsync {
		r.Get(apiRunsPrefix, api.listRuns)
		r.Get(apiRunsPrefix+"/{runId}", api.getRun)
		r.Get(apiRunsPrefix+"/{runId}/output", api.getRunOutput)
		r.Post(apiRunsPrefix+"/{runId}/cancel", api.cancelRun)
	}
	return r
}

// runAction resolves a run id to its action, authorizing the caller with the
// action's permit; a run of an action the caller cannot run is not found
func (api *appAPI) runAction(w http.ResponseWriter, r *http.Request) (*Action, *types.ActionRun, bool) {
	runId := chi.URLParam(r, "runId")
	for _, act := range api.actions {
		if !act.IsAsync() {
			continue
		}
		run, err := act.LoadRun(r.Context(), runId, false)
		if err != nil {
			continue
		}
		if !act.authorizeAction(w, r, true) {
			return nil, nil, false
		}
		return act, run, true
	}
	writeJSONError(w, fmt.Sprintf("run %s not found", runId), http.StatusNotFound)
	return nil, nil, false
}

// listRuns lists the async runs of the app's actions the caller may run;
// ?action=<path> selects one action, ?status= filters, ?limit= caps
func (api *appAPI) listRuns(w http.ResponseWriter, r *http.Request) {
	query := r.URL.Query()
	actionPath := query.Get("action")
	if actionPath != "" && !strings.HasPrefix(actionPath, "/") {
		actionPath = "/" + actionPath
	}
	limit, _ := strconv.Atoi(query.Get("limit"))
	runs := make([]types.ActionRun, 0)
	for _, act := range api.actions {
		if !act.IsAsync() || (actionPath != "" && act.actionPath != actionPath) {
			continue
		}
		authorized, err := act.Authorized(r.Context())
		if err != nil {
			writeJSONError(w, err.Error(), http.StatusInternalServerError)
			return
		}
		if !authorized {
			continue
		}
		actionRuns, err := act.ListRuns(r.Context(), query.Get("status"), limit)
		if err != nil {
			writeJSONError(w, err.Error(), http.StatusInternalServerError)
			return
		}
		for _, run := range actionRuns {
			runs = append(runs, run.BasicView())
		}
	}
	slices.SortFunc(runs, func(a, b types.ActionRun) int {
		return b.StartedAt.Compare(a.StartedAt)
	})
	if limit > 0 && len(runs) > limit {
		runs = runs[:limit]
	}
	writeJSON(w, http.StatusOK, types.ActionRunsResponse{Runs: runs})
}

// getRun returns a run document; ?wait=<duration> waits for the run to end
func (api *appAPI) getRun(w http.ResponseWriter, r *http.Request) {
	act, run, ok := api.runAction(w, r)
	if !ok {
		return
	}
	if wait := parseWait(r.URL.Query().Get("wait")); wait > 0 && run.IsActive() {
		var err error
		if run, err = act.WaitRun(r.Context(), run.Id, wait, true); err != nil {
			writeJSONError(w, err.Error(), http.StatusNotFound)
			return
		}
	} else {
		var err error
		if run, err = act.LoadRun(r.Context(), run.Id, true); err != nil {
			writeJSONError(w, err.Error(), http.StatusNotFound)
			return
		}
	}
	code := http.StatusOK
	if run.IsActive() {
		code = http.StatusAccepted
	}
	writeJSON(w, code, act.RunAPIResult(run))
}

// getRunOutput returns the output of a run from ?since=
func (api *appAPI) getRunOutput(w http.ResponseWriter, r *http.Request) {
	act, run, ok := api.runAction(w, r)
	if !ok {
		return
	}
	run, err := act.LoadRun(r.Context(), run.Id, true)
	if err != nil {
		writeJSONError(w, err.Error(), http.StatusNotFound)
		return
	}
	since, _ := strconv.ParseInt(r.URL.Query().Get("since"), 10, 64)
	WriteRunOutput(w, run, since)
}

// cancelRun cancels an active run
func (api *appAPI) cancelRun(w http.ResponseWriter, r *http.Request) {
	act, run, ok := api.runAction(w, r)
	if !ok {
		return
	}
	if _, invErr := act.CancelRun(r.Context(), run.Id); invErr != nil {
		writeJSONError(w, invErr.Msg, invErr.Code)
		return
	}
	run, err := act.WaitRun(r.Context(), run.Id, 2*time.Second, false)
	if err != nil {
		writeJSONError(w, fmt.Sprintf("run canceled, record unavailable: %s", err), http.StatusNotFound)
		return
	}
	writeJSON(w, http.StatusOK, types.ActionRunResponse{Run: run.BasicView()})
}

func writeJSON(w http.ResponseWriter, code int, v any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(code)
	_ = json.MarshalWrite(w, v) // response is already committed, error cannot be reported
}

func writeJSONError(w http.ResponseWriter, msg string, code int) {
	writeJSON(w, code, map[string]any{"error": msg})
}

func isOptionsParam(name string) bool {
	return strings.HasPrefix(name, OPTIONS_PREFIX) || strings.HasPrefix(name, OPTIONS_PREFIX_UNDERSCORE)
}

func requestHasJSONBody(r *http.Request) bool {
	mediaType, _, err := mime.ParseMediaType(r.Header.Get("Content-Type"))
	if err != nil {
		return false
	}
	return mediaType == "application/json"
}

// buildArgsFromJSON updates args with the values from the JSON request body.
// Values not present in the body retain the app level param values, unlike the
// form UI where all form fields are always submitted. Dropdown params are
// validated against the configured options, same as the form UI
func (a *Action) buildArgsFromJSON(args starlark.StringDict, body map[string]jsontext.Value, options map[string][]string) error {
	visible := map[string]apptype.AppParam{}
	for _, p := range a.params {
		if a.hidden[p.Name] || isOptionsParam(p.Name) {
			continue
		}
		visible[p.Name] = p
	}

	keys := slices.Collect(maps.Keys(body))
	slices.Sort(keys)
	for _, name := range keys {
		param, ok := visible[name]
		if !ok {
			return fmt.Errorf("unknown param %s", name)
		}

		value := body[name]
		if value.Kind() == 'n' {
			continue // null, use the app level param value
		}

		if param.DisplayType == apptype.DisplayTypeFileUpload {
			// File params cannot be set through JSON, the value is a server side
			// file path which the client should not control
			return fmt.Errorf("param %s is a file upload param, submit using multipart/form-data", name)
		}

		newVal, err := jsonValueToParamType(param, value)
		if err != nil {
			return err
		}

		// Dropdown params are strict by default: a non-empty value must be one
		// of the configured options (COMBO display type allows free text)
		if opts := options[name]; len(opts) > 0 && param.DisplayType != apptype.DisplayTypeCombo {
			strVal := newVal.String()
			if s, ok := newVal.(starlark.String); ok {
				strVal = string(s)
			}
			if strVal != "" && !slices.Contains(opts, strVal) {
				return fmt.Errorf("invalid value for %s: must be one of the configured options", name)
			}
		}
		args[name] = newVal
	}
	return nil
}

// jsonValueToParamType converts a raw JSON body value to the starlark value for
// the param type. String values are coerced the same way as form submissions.
// Integers are decoded from the JSON text without going through a float, so
// large values keep their precision and out of range values are rejected
func jsonValueToParamType(param apptype.AppParam, value jsontext.Value) (starlark.Value, error) {
	if value.Kind() == '"' {
		var strValue string
		if err := json.Unmarshal(value, &strValue); err != nil {
			return nil, fmt.Errorf("param %s: %w", param.Name, err)
		}
		return apptype.ParamStringToType(param.Name, param.Type, strValue)
	}

	switch param.Type {
	case starlark_type.STRING:
		return nil, fmt.Errorf("param %s must be a string", param.Name)
	case starlark_type.INT:
		var intValue int64
		if value.Kind() != '0' || json.Unmarshal(value, &intValue) != nil {
			return nil, fmt.Errorf("param %s must be an integer", param.Name)
		}
		return starlark.MakeInt64(intValue), nil
	case starlark_type.BOOLEAN:
		switch value.Kind() {
		case 't':
			return starlark.True, nil
		case 'f':
			return starlark.False, nil
		default:
			return nil, fmt.Errorf("param %s must be a boolean", param.Name)
		}
	case starlark_type.LIST:
		var listValue []any
		if value.Kind() != '[' || json.Unmarshal(value, &listValue) != nil {
			return nil, fmt.Errorf("param %s must be a list", param.Name)
		}
		return starlark_type.FromGo(listValue)
	case starlark_type.DICT:
		var dictValue map[string]any
		if value.Kind() != '{' || json.Unmarshal(value, &dictValue) != nil {
			return nil, fmt.Errorf("param %s must be a dict", param.Name)
		}
		return starlark_type.FromGo(dictValue)
	default:
		var goValue any
		if err := json.Unmarshal(value, &goValue); err != nil {
			return nil, fmt.Errorf("param %s: %w", param.Name, err)
		}
		return starlark_type.FromGo(goValue)
	}
}

// APIResult builds the JSON response document and the http status for a run
// or validate outcome. Param validation errors are reported with a 422 status
func (a *Action) APIResult(o *Outcome, isValidate bool) (map[string]any, int) {
	errorMsgs := map[string]string{}
	for _, param := range a.params {
		if isOptionsParam(param.Name) {
			continue
		}
		if o.ParamErrors[param.Name] != nil {
			errorMsgs[param.Name] = fmt.Sprintf("%s", o.ParamErrors[param.Name])
		}
	}

	response := map[string]any{
		"status": o.Status,
	}

	code := http.StatusOK
	if len(errorMsgs) > 0 {
		response["param_errors"] = errorMsgs
		code = http.StatusUnprocessableEntity
	} else if !isValidate {
		response["report"] = effectiveReport(o.Report, o.ValuesMap, o.ValuesStr)
		if len(o.ValuesStr) > 0 {
			response["values"] = o.ValuesStr
		} else if o.ValuesMap != nil {
			response["values"] = o.ValuesMap
		} else {
			response["values"] = []any{}
		}
	}

	return response, code
}

// effectiveReport resolves the AUTO report type to the actual report type,
// using the same rules as the form UI rendering
func effectiveReport(report string, valuesMap []map[string]any, valuesStr []string) string {
	if report != apptype.AUTO {
		return report
	}
	if len(valuesStr) > 0 || len(valuesMap) == 0 {
		return apptype.TEXT
	}

	for _, v := range valuesMap[0] {
		if v == nil {
			continue
		}
		switch v.(type) {
		case int, string, bool:
		default:
			return apptype.JSON
		}
	}
	return apptype.TABLE
}

// writeAPISuggestResponse writes the JSON response for the suggest API
func (a *Action) writeAPISuggestResponse(w http.ResponseWriter, retVal starlark.Value) {
	response, err := a.SuggestResult(retVal)
	if err != nil {
		writeJSONError(w, err.Msg, err.Code)
		return
	}
	writeJSON(w, http.StatusOK, response)
}

// SuggestResult builds the JSON response document for a suggest handler
// response. The response params are filtered the same way as the form UI
// suggest handling
func (a *Action) SuggestResult(retVal starlark.Value) (map[string]any, *InvokeError) {
	ret, err := starlark_type.ToGo(retVal)
	if err != nil {
		return nil, invokeErr(http.StatusInternalServerError, "error unmarshalling suggest response: %s", err)
	}

	if message, retIsString := ret.(string); retIsString {
		// No suggestions available
		return map[string]any{"status": message}, nil
	}

	retDict := map[string]any{}
	switch retType := ret.(type) {
	case map[string]any:
		retDict = retType
	case map[string]string:
		for k, v := range retType {
			retDict[k] = v
		}
	case map[string]int:
		for k, v := range retType {
			retDict[k] = v
		}
	case map[string]bool:
		for k, v := range retType {
			retDict[k] = v
		}
	case map[string][]string:
		for k, v := range retType {
			retDict[k] = v
		}
	default:
		return nil, invokeErr(http.StatusInternalServerError, "invalid suggest response type: %T, expected dict", retType)
	}

	paramMap := map[string]bool{}
	for _, p := range a.params {
		paramMap[p.Name] = true
	}

	params := map[string]any{}
	for key, value := range retDict {
		if !paramMap[key] || isOptionsParam(key) {
			a.Info().Msgf("ignoring suggest response for param: %s", key)
			continue
		}
		params[key] = value
	}

	return map[string]any{"status": "Suggesting values", "params": params}, nil
}

type apiActionInfo struct {
	Name         string `json:"name"`
	Description  string `json:"description,omitempty"`
	Path         string `json:"path"`
	ValidatePath string `json:"validate_path"`
	SuggestPath  string `json:"suggest_path,omitempty"`
	UIPath       string `json:"ui_path"`
	Suggest      bool   `json:"suggest"`
	Authorized   bool   `json:"authorized"`
}

// apiPath returns the full API path for an action under the given operation prefix
func (api *appAPI) apiPath(prefix string, act *Action) string {
	return path.Join(api.appPath, API_PATH, prefix, act.actionPath)
}

// authorized reports whether the current user has access to the action, as
// per the action's permit list
func (api *appAPI) authorized(r *http.Request, act *Action) (bool, error) {
	return act.Authorized(r.Context())
}

// describe lists the actions available in the app, with their API paths
func (api *appAPI) describe(w http.ResponseWriter, r *http.Request) {
	infos := make([]apiActionInfo, 0, len(api.actions))
	for _, act := range api.actions {
		authorized, err := api.authorized(r, act)
		if err != nil {
			writeJSONError(w, err.Error(), http.StatusInternalServerError)
			return
		}

		uiPath := act.pagePath
		if uiPath == "" {
			uiPath = "/"
		}
		info := apiActionInfo{
			Name:         act.name,
			Description:  act.description,
			Path:         api.apiPath(apiActionsPrefix, act),
			ValidatePath: api.apiPath(apiValidatePrefix, act),
			UIPath:       uiPath,
			Suggest:      act.suggest != nil,
			Authorized:   authorized,
		}
		if act.suggest != nil {
			info.SuggestPath = api.apiPath(apiSuggestPrefix, act)
		}
		infos = append(infos, info)
	}

	writeJSON(w, http.StatusOK, map[string]any{"app": api.appName, "actions": infos})
}

// paramDefault returns the app level value for a param, converted to its
// native type. The string value is returned if the conversion fails
func (a *Action) paramDefault(p apptype.AppParam) any {
	valueStr, ok := a.paramValuesStr[p.Name]
	if !ok {
		return nil
	}
	value, err := apptype.ParamStringToType(p.Name, p.Type, valueStr)
	if err != nil {
		return valueStr
	}
	goValue, err := starlark_type.ToGo(value)
	if err != nil {
		return valueStr
	}
	return goValue
}

// apiGetSchema returns the param definitions for an action
func (a *Action) apiGetSchema(w http.ResponseWriter, r *http.Request) {
	if !a.authorizeAction(w, r, true) {
		return
	}

	schema, err := a.Schema()
	if err != nil {
		writeJSONError(w, err.Error(), http.StatusInternalServerError)
		return
	}
	writeJSON(w, http.StatusOK, schema)
}

// ActionSchema has the param definitions for an action
type ActionSchema struct {
	Name        string              `json:"name"`
	Description string              `json:"description"`
	Params      []types.ActionParam `json:"params"`
	Suggest     bool                `json:"suggest"`
}

// Schema returns the param definitions for an action. Hidden params and the
// options params are not included. The caller is expected to have checked
// Authorized, the definitions and defaults of restricted actions are not
// to be disclosed
func (a *Action) Schema() (*ActionSchema, error) {
	options, err := a.paramOptions()
	if err != nil {
		return nil, err
	}

	params := make([]types.ActionParam, 0, len(a.params))
	for _, p := range a.params {
		if isOptionsParam(p.Name) || a.hidden[p.Name] {
			continue
		}
		info := types.ActionParam{
			Name:        p.Name,
			Type:        string(p.Type),
			Description: p.Description,
			Default:     a.paramDefault(p),
			Required:    p.Required,
			DisplayType: string(p.DisplayType),
			Options:     options[p.Name],
		}
		if p.DisplayType == apptype.DisplayTypePassword {
			info.Default = nil // the app level value of a password param is not disclosed
		}
		params = append(params, info)
	}

	return &ActionSchema{
		Name:        a.name,
		Description: a.description,
		Params:      params,
		Suggest:     a.suggest != nil,
	}, nil
}

// InputJSONSchema returns the JSON schema of the args object for the action:
// the request body schema in the OpenAPI spec and the MCP tool input schema.
// File upload params cannot be carried in a JSON document, they are left out
// when skipFiles is set (MCP)
func (a *Action) InputJSONSchema(skipFiles bool) (map[string]any, error) {
	options, err := a.paramOptions()
	if err != nil {
		return nil, err
	}

	properties := map[string]any{}
	required := []string{}
	for _, p := range a.params {
		if isOptionsParam(p.Name) || a.hidden[p.Name] {
			continue
		}
		if skipFiles && p.DisplayType == apptype.DisplayTypeFileUpload {
			continue
		}
		defaultVal := a.paramDefault(p)
		if p.DisplayType == apptype.DisplayTypePassword {
			defaultVal = nil
		}
		properties[p.Name] = paramJSONSchema(p, options[p.Name], defaultVal)
		if p.Required && a.paramValuesStr[p.Name] == "" {
			// A required param with an app level value does not have to be passed
			required = append(required, p.Name)
		}
	}

	schema := map[string]any{"type": "object", "properties": properties}
	if len(required) > 0 {
		schema["required"] = required
	}
	return schema, nil
}

// HasRequiredFileParam reports whether the action has a required file upload
// param, such an action cannot be called with a JSON args document
func (a *Action) HasRequiredFileParam() bool {
	for _, p := range a.params {
		if p.DisplayType == apptype.DisplayTypeFileUpload && p.Required && !a.hidden[p.Name] {
			return true
		}
	}
	return false
}

// HasParam reports whether the action has a visible param with the name
func (a *Action) HasParam(name string) bool {
	for _, p := range a.params {
		if p.Name == name && !a.hidden[p.Name] && !isOptionsParam(p.Name) {
			return true
		}
	}
	return false
}

// Name returns the action name
func (a *Action) Name() string { return a.name }

// Description returns the action description
func (a *Action) Description() string { return a.description }

// Path returns the action path within the app
func (a *Action) Path() string { return a.actionPath }

// Permit returns the custom permissions of which the caller needs one, empty
// when the action is not restricted
func (a *Action) Permit() []string { return slices.Clone(a.permit) }

// HasSuggest reports whether the action has a suggest handler
func (a *Action) HasSuggest() bool { return a.suggest != nil }

// paramJSONSchema returns the OpenAPI schema for a param
func paramJSONSchema(p apptype.AppParam, options []string, defaultVal any) map[string]any {
	schema := map[string]any{}
	switch p.Type {
	case starlark_type.INT:
		schema["type"] = "integer"
	case starlark_type.FLOAT:
		schema["type"] = "number"
	case starlark_type.BOOLEAN:
		schema["type"] = "boolean"
	case starlark_type.LIST:
		schema["type"] = "array"
		schema["items"] = map[string]any{} // list elements can be of any type
	case starlark_type.DICT:
		schema["type"] = "object"
	case starlark_type.DATETIME:
		schema["type"] = "string"
		schema["format"] = "date-time"
	default:
		schema["type"] = "string"
	}

	description := p.Description
	if p.DisplayType == apptype.DisplayTypeFileUpload {
		description = strings.TrimSpace(description + " (file upload param, submit using multipart/form-data)")
	}
	if description != "" {
		schema["description"] = description
	}
	if len(options) > 0 {
		if p.DisplayType == apptype.DisplayTypeCombo {
			// COMBO allows free text, the options are suggestions only. OpenAPI
			// 3.0 schemas support a single example, the full list is in an extension
			schema["example"] = options[0]
			schema["x-options"] = options
		} else {
			schema["enum"] = options
		}
	}
	if defaultVal != nil {
		schema["default"] = defaultVal
	}
	return schema
}

// operationId returns the OpenAPI operationId for an operation on an action.
// name is the tool name of the action (ToolNames): the OpenAPI spec, the CLI
// and the MCP tools name an action the same way
func operationId(op string, name string) string {
	return op + "_" + name
}

// openAPISpec serves the OpenAPI 3.0 spec for the app actions
func (api *appAPI) openAPISpec(w http.ResponseWriter, r *http.Request) {
	spec, err := OpenAPISpec(r.Context(), api.appName, api.appPath, api.actions)
	if err != nil {
		writeJSONError(w, err.Error(), http.StatusInternalServerError)
		return
	}
	writeJSON(w, http.StatusOK, spec)
}

// OpenAPISpec generates the OpenAPI 3.0 spec for the app actions. Only the
// actions the caller (the identity in ctx) is authorized for are included,
// the param definitions and defaults of restricted actions are not disclosed
func OpenAPISpec(ctx context.Context, appName, appPath string, actions []*Action) (map[string]any, error) {
	api := &appAPI{appName: appName, appPath: appPath, actions: actions}
	resultResponse := map[string]any{
		"description": "Action result. A handler returning a stream (ace.result stream=) " +
			"answers with chunked text/plain: the command output as produced, the result " +
			"status text in the OpenRun-Action-Status header and the exit status in the " +
			"OpenRun-Exit-Status trailer (absent when the stream was cut)",
		"content": map[string]any{
			"application/json": map[string]any{
				"schema": map[string]any{"$ref": "#/components/schemas/ActionResult"},
			},
			"text/plain": map[string]any{
				"schema": map[string]any{"type": "string"},
			},
		},
	}
	errorContent := map[string]any{
		"application/json": map[string]any{
			"schema": map[string]any{"$ref": "#/components/schemas/Error"},
		},
	}
	execResponses := map[string]any{
		"200": resultResponse,
		"400": map[string]any{"description": "Invalid request", "content": errorContent},
		"422": map[string]any{
			"description": "Param validation errors",
			"content": map[string]any{
				"application/json": map[string]any{
					"schema": map[string]any{"$ref": "#/components/schemas/ActionResult"},
				},
			},
		},
		"500": map[string]any{"description": "Action failed", "content": errorContent},
	}

	names := ToolNames(api.actions)
	paths := map[string]any{}
	for _, act := range api.actions {
		authorized, err := act.Authorized(ctx)
		if err != nil {
			return nil, err
		}
		if !authorized {
			continue
		}

		inputSchema, err := act.InputJSONSchema(false)
		if err != nil {
			return nil, err
		}

		requestBody := map[string]any{
			"content": map[string]any{
				"application/json": map[string]any{
					"schema": inputSchema,
				},
			},
		}

		paths[api.apiPath(apiActionsPrefix, act)] = map[string]any{
			"get": map[string]any{
				"operationId": operationId("schema", names[act]),
				"summary":     "Get the param definitions for " + act.name,
				"responses": map[string]any{
					"200": map[string]any{"description": "Action param definitions"},
				},
			},
			"post": map[string]any{
				"operationId": operationId("run", names[act]),
				"summary":     act.name,
				"description": act.description,
				"requestBody": requestBody,
				"responses":   execResponses,
			},
		}
		paths[api.apiPath(apiValidatePrefix, act)] = map[string]any{
			"post": map[string]any{
				"operationId": operationId("validate", names[act]),
				"summary":     "Validate the params for " + act.name,
				"requestBody": requestBody,
				"responses":   execResponses,
			},
		}
		if act.suggest != nil {
			// Suggest takes a partial set of args, no param is required
			suggestSchema := maps.Clone(inputSchema)
			delete(suggestSchema, "required")
			suggestBody := map[string]any{
				"content": map[string]any{
					"application/json": map[string]any{"schema": suggestSchema},
				},
			}
			paths[api.apiPath(apiSuggestPrefix, act)] = map[string]any{
				"post": map[string]any{
					"operationId": operationId("suggest", names[act]),
					"summary":     "Suggest param values for " + act.name,
					"requestBody": suggestBody,
					"responses":   execResponses,
				},
			}
		}
	}

	spec := map[string]any{
		"openapi": "3.0.3",
		"info": map[string]any{
			"title":   api.appName,
			"version": "1.0.0",
		},
		"paths": paths,
		"components": map[string]any{
			"schemas": map[string]any{
				"ActionResult": map[string]any{
					"type": "object",
					"properties": map[string]any{
						"status": map[string]any{"type": "string"},
						"report": map[string]any{"type": "string"},
						"values": map[string]any{"type": "array", "items": map[string]any{}},
						"param_errors": map[string]any{
							"type":                 "object",
							"additionalProperties": map[string]any{"type": "string"},
						},
					},
				},
				"Error": map[string]any{
					"type": "object",
					"properties": map[string]any{
						"error": map[string]any{"type": "string"},
					},
				},
			},
		},
	}

	return spec, nil
}
